README.md

Ref: https://github.com/aragon/issues/issues/76

Add os compatibility note

---

src/components/MenuPanel/MenuPanelAppGroup.js

A pressed state on apps, as discussed in https://github.com/aragon/aragon/pull/74#issuecomment-351894788

MenuPanel: add pressed states on apps

---

package.json
src/App.js
src/apps/Permissions/AssignPermission.js
src/apps/Permissions/InstancePermissions.js
src/apps/Permissions/List.js
src/apps/Permissions/ListItem.js
src/apps/Permissions/Permissions.js
src/apps/Permissions/PermissionsHome.js
src/apps/Permissions/RevokeFooter.js
src/apps/demo/App.js
src/components/App/AppIFrame.js
src/components/App/AppLoadingProgressBar.js
src/components/App404/App404.js
src/components/App404/EmptyAppCard.js
src/components/Badge/Badge.js
src/components/CircleGraph.js
src/components/ColumnSection/ColumnSection.js
src/components/ExpandableBox/ExpandableBox.js
src/components/Home/Home.js
src/components/Home/HomeCard.js
src/components/Home/PricesBar.js
src/components/Home/Token.js
src/components/MenuPanel/MenuPanel.js
src/components/MenuPanel/MenuPanelAppGroup.js
src/components/MenuPanel/MenuPanelInstance.js
src/components/NotificationsPanel/NotificationItem.js
src/components/NotificationsPanel/NotificationsPanel.js
yarn.lock

Requires a rebuild and re-link of `@aragon/ui` to work with https://github.com/aragon/aragon-ui/pull/80 merged.

Install styled-components

---

src/demo-state.js

Points to the Voting app in development mode (`http://localhost:3001`).

Enable the voting app (dev only)

---

src/demo-state.js

Points to the Finance app in development mode (`http://localhost:3002`).

Enable the Finance app (dev only)

---

src/demo-state.js

Makes it easier to share the app.

Use the current hostname for apps src (dev only)

---

src/components/App/AppIFrame.js
src/components/SignerPanel/SignerPanelContent.js

Unifies the style of handlers passed down as props.

Use defaultProps to set noop defaults

---

src/App.js
src/aragonjs-wrapper.js
src/environment.js

Puts all the environment-related constants in its own module.
Also uses the app's `appId` (which should be stable, as a APM-constant) to identify apps.

Encapsulate environment

---

src/Wrapper.js
src/aragonjs-wrapper.js
src/components/App/AppIFrame.js

Small consistency thing; we could also change everything to `Iframe` but I find that looks weirder 🤷‍♂️ .

Iframe -> IFrame

---

.babelrc
package.json
yarn.lock

Also includes the styled-components babel plugin.

Add dev dependencies explicitly

---

src/aragonjs-wrapper.js

Using the metamask provider seems to work if we just use it for signing and accounts 🤗

Use metamask provider for accounts and signing

---

package.json
src/aragonjs-wrapper.js
src/environment.js
src/utils.js
src/worker-utils.js
yarn.lock

Requires https://github.com/aragon/aragon/pull/125, https://github.com/aragon/aragon/pull/126
🤞the voting app will just work with this. Seems to start local bg scripts OK, so... 🤞🤞🤞

Start a WebWorker for apps that define their own webworkers

---

src/environment.js

Adds local overrides for the Token Manager.

Add Token Manager to dev environment

---

package.json
src/App.js
src/Wrapper.js
src/components/MenuPanel/MenuPanel.js
src/components/NotificationsPanel/NotificationItem.js
src/components/NotificationsPanel/NotificationsPanel.js
src/demo-state.js
src/routing.js
yarn.lock

Requires https://github.com/aragon/aragon.js/pull/60, https://github.com/aragon/aragon.js/pull/61, https://github.com/aragon/aragon-ui/pull/128, https://github.com/aragon/aragon-ui/pull/129, https://github.com/aragon/aragon-ui/pull/140, #136.
Before merging:

Connect notifications to aragon.js

---

src/Wrapper.js

It'd also be really nice to have this load a message (e.g. "Loading...") or display a gif or something :).

Hide App404 until apps have loaded

---

src/onboarding/Onboarding.js
src/onboarding/templates/democracy/index.js
src/onboarding/templates/multisig/index.js

In the voting settings screen from the democracy template, the support and min. quorum fields are now inter dependents.

Allow to have constrained field updates in the templates

---

src/App.js
src/Wrapper.js
src/aragonjs-wrapper.js
src/components/SignerPanel/SignerPanelContent.js
src/web3-utils.js

Also sets a `walletWeb3` to use for signing.

Show account locked in signer

---

src/Wrapper.js

Aragon.js now supports an accounts observable, so we don't need this anymore :).

Wrapper: remove accounts messaging to apps

---

src/aragonjs-wrapper.js
src/environment.js

1. TokenManager
2. Finance
3. Voting

Sort known apps in the menu

---

src/Wrapper.js
src/apps/Settings/Settings.js

Also disables the currency dropdown (only USD is available at the moment).

Add a list of apps in the settings

---

src/aragonjs-wrapper.js
src/environment.js

Overrides are better now that we want to override default production settings.

Environment uses app overrides rather than defaults

---

package.json
src/Wrapper.js
src/apps/Settings/Settings.js
src/components/AppLayout/AppLayout.js
src/components/ComingSoon/ComingSoon.js
src/components/Home/Home.js
src/components/MenuPanel/MenuPanel.js

The coming soon screen is identical to the home screen:

Coming soon screens for apps and permissions

---

README.md

Fixes https://github.com/aragon/aragon/issues/176

Fix broken README.md links

---

src/App.js
src/aragonjs-wrapper.js
src/utils.js

Just a quick `log()` utility for now.

Remove console.log() calls in production

---

src/App.js
src/Wrapper.js
src/apps/Settings/Settings.js
src/aragonjs-wrapper.js
src/components/ComingSoon/ComingSoon.js
src/components/MenuPanel/MenuPanel.js
src/components/MenuPanel/MenuPanelAppsLoader.js
src/onboarding/Start.js

Not 100% satisfied with the way it looks but we can refine it later.

Menu apps loader

---

src/Wrapper.js
src/components/SignerPanel/SignerPanelContent.js

Still needs a bit of clean up and it currently only handles 1 path (since Aragon.js does not calculate multiple possible paths). Will make it a bit more future proof
Closes #168

Make signer view display path (if any)

---

src/components/LoadingRing.js
src/components/MenuPanel/MenuPanelAppsLoader.js
src/onboarding/Domain.js
src/onboarding/Onboarding.js
src/onboarding/Start.js
src/onboarding/templates/democracy/index.js
src/onboarding/templates/multisig/index.js

Template fields update (WIP)

---

src/Wrapper.js
src/apps/Settings/Settings.js

Settings: new section to explain how to send Ethers

---

src/Wrapper.js
src/components/Home/Home.js
src/components/Home/HomeCard.js
src/demo-state.js

Add shortcuts + loading on the home app

---

src/apps/Settings/Settings.js

The button clears localStorage + refreshes the page.

Settings: add a clear cache button (+ structure adjustments)

---

src/components/MenuPanel/MenuPanel.js
src/components/MenuPanel/MenuPanelAppGroup.js

See https://github.com/aragon/aragon/issues/191

Coming soon in the menu

---

README.md
src/apps/Settings/Settings.js
src/environment.js
src/local-settings.js
src/network-config.js
src/onboarding/Start.js
src/utils.js

Also adds some development warnings if some configuration is obviously wrong.

Refactor network environment into its own module

---

README.md
src/apps/Settings/Settings.js
src/environment.js
src/local-settings.js
src/network-config.js
src/onboarding/Start.js
src/utils.js

Also adds some better error messaging when using the wrong chain.

Add ability to set the ENS registry address and expected network type via env variables

---

package.json

:pray:
Some testing doesn't reveal anything obviously broken... so let's hope nothing is from the update :D.

Upgrade web3 to 1.0.0-beta.34

---

src/Wrapper.js

Custom apps don't have instanceId, so are not being found.

Fix apps finding again

---

src/onboarding/Domain.js
src/onboarding/Launch.js
src/onboarding/Onboarding.js
src/onboarding/Sign.js
src/onboarding/Start.js
src/onboarding/Template.js
src/onboarding/templates/democracy/ConfigureTokenName.js
src/onboarding/templates/democracy/ConfigureVotingDefaults.js
src/onboarding/templates/multisig/ConfigureMultisigAddresses.js
src/onboarding/templates/multisig/ConfigureMultisigToken.js

- Unmount the component when possible
- Tweak the reveal transition
- Remove the will-change properties

Onboarding: optimize rendering

---

src/apps/Settings/DaoSettings.js

Settings: only display checksummed addresses

---

.eslintrc
src/Wrapper.js

Removes most of the annoying console messages from react-scripts.
cc @bpierre

Add react-app config to eslint and fix some unused variables

---

package.json

Add build script for mainnet infura

---

README.md
scripts/launch-local.sh
src/environment.js
src/local-settings.js

Made unnecessary by changes to apm.js (https://github.com/aragon/apm.js/pull/16)
cc @bpierre

Remove IPFS rpc configuration

---

src/aragonjs-wrapper.js
src/utils.js

Support HTTP URLs for app locations

---

package.json
src/aragonjs-wrapper.js
src/onboarding/Start.js

With this, all dependencies on `bignumber.js` should be removed :tada:!
Pins `bn.js` to be consistent with web3.js's dependency.

Use bn.js instead of bignumber.js

---

src/components/Home/Home.js

Otherwise we get a nasty memory leak error :(

Home: clear timeout when unmounting

---

package.json
src/permissions.js

@izqui @sohkai What do you think about running eslint on every commit?
It might require to stash more when working on different things at the same time, but I always forget to run it.
We could also run it on push only: until we have tests, a commit that doesn’t pass eslint is ok IMO.

Run npm test on pre-commit

---

src/App.js
src/Wrapper.js
src/components/Home/Home.js

Mention the DAO name on the home app

---

src/apps/Permissions/AppPermissions.js
src/apps/Permissions/AppRoles.js
src/apps/Permissions/AssignPermissionPanel.js
src/apps/Permissions/EntityPermissions.js
src/apps/Permissions/Home/BrowseByEntity.js
src/apps/Permissions/ManageRolePanel.js

Permissions fixes

---

src/components/DeprecatedBanner/DeprecatedBanner.js

Updates the blog post URL and date.

Update deprecation notice

---

src/math-utils.js
src/onboarding/Start.js

Fixes #307, supersedes formatting changes in https://github.com/aragon/aragon/pull/331.

Add `formatNumber()` util

---

src/Wrapper.js
src/apps/Apps/Apps.js
src/components/MenuPanel/MenuPanel.js

Main change: avoid using `height: 100%` and use `flex-grow: 1` instead (`height: 100%` can lose its ability to shrink in some cases).

More layout and minor fixes

---

src/Wrapper.js
src/components/SignerPanel/SignerPanelContent.js

Requires https://github.com/aragon/aragon.js/pull/167
@sohkai @izqui `approve()` works ✨ but for some reason the second transaction fails, I’m trying to figure out why 🤔
Edit: it was just me mixing two token names 😅

Pretransactions support (working!)

---

src/aragonjs-wrapper.js
src/onboarding/templates/democracy/ConfigureVotingDefaults.js
src/onboarding/templates/democracy/index.js

Small tweaks to the democracy onboarding to mimic the new strict thresholds in the Voting contract (invalidate 100%).

Democracy onboarding ensure thresholds

---

README.md
src/App.js
src/environment.js
src/onboarding/Onboarding.js
src/onboarding/Start.js

Also add a link to the demo DAO (if the `ARAGON_DEMO_DAO` env var is set).
Fixes #382.

Onboarding: network switcher + new layout

---

src/onboarding/templates/multisig/ConfigureMultisigAddresses.js
src/onboarding/templates/multisig/index.js

Implements the error validation part of #238.
Not the nicest, but uses the current wiring on the onboarding components to also include some error validation.
The inputs don't give us a lot of space to play around with, so it does look a little cramped:
---------------
----------------

Multisig: detect duplicate addresses

---

src/environment.js
src/network-config.js
src/onboarding/Start.js
src/utils.js

Fix network detection

---

src/components/Error/DAONotFoundError.js

Add some actions below the “DAO not found” error screen

---

package.json
src/components/Home/Home.js

v0.6 — Alba

---

src/network-config.js

"Connect to the main network" may be a bit confusing.

Fix humanized mainnet name

---

src/apps/Settings/DaoSettings.js

🙈 oops, we were using the same proxy address for multiple instances of the same app.

Settings: use the unique proxy address for each app instance

---

src/apps/Apps/Apps.js

Updated planning suite name and URL

---

src/apps/Permissions/ManageRolePanel.js

Entity input component when changing or initializing permission manager

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/miscellaneous.md

Provides a structure that can be used for new issues that are created.

Update issue templates

---

src/apps/Permissions/EntityPermissions.js
src/apps/Permissions/Permissions.js

Permissions: clarify heading for permissions set on entity

---

package.json
src/environment.js
src/web3-utils.js

With these changes the responsive app works in `Coinbase Wallet`, `Cipher` and `Status`.

Mobile browsers web3 provider

---

src/onboarding/Onboarding.js
src/onboarding/Start.js

Responsive onboarding landing page

---

src/apps/Permissions/AddPermissionButton.js
src/apps/Permissions/AppInstanceLabel.js
src/apps/Permissions/AppPermissions.js
src/apps/Permissions/AppRoles.js
src/apps/Permissions/EmptyBlock.js
src/apps/Permissions/EntityPermissions.js
src/apps/Permissions/Home/BrowseByApp.js
src/apps/Permissions/Home/BrowseByEntity.js
src/apps/Permissions/Home/EntityRow.js
src/apps/Permissions/Home/ViewDetailsButton.js
src/apps/Permissions/ManageRolePanel.js
src/apps/Permissions/NavigationItem.js
src/apps/Permissions/Permissions.js
src/apps/Permissions/Screen.js
src/apps/Permissions/Section.js
src/apps/Permissions/Table.js

Responsive permissions app

---

src/components/SignerPanel/ConfirmTransaction.js
src/utils.js

Users of Aragon Desktop are basically only able to use it with Frame.

feat: suggest users install frame when using Aragon Desktop

---

src/onboarding/Start.js

Onboarding: position demo link away from open organization button in Start

---

package.json

chore: release 0.6.3

---

src/components/MenuPanel/MenuPanelAppGroup.js

Fix for cosmetic issue https://github.com/aragon/aragon/issues/326

fix: correct active menu item icon image color using css filter (#326)

---

src/apps/Settings/DaoSettings.js

DaoSettings: update inline styles to styled component

---

src/components/MenuPanel/MenuPanel.js

- Fix the transition between autoclosing / fixed modes.
- Fix the panel min-width on medium+ widths.

MenuPanel tweaks

---

package.json

chore: upgrade @aragon/cli for publishing

---

src/index.js

Oops, forgot to use a `indexedDB.databases()` correctly 🤦‍♂️

fix: call indexedDB.databases() correctly

---

src/apps/Settings/DaoSettings.js

DaoSettings: add bottom margin on app items

---

src/apps/Permissions/AppCard.js

Adds a `System App` label to apps without a fronend on Permissions

Permissions: added system and background app labels

---

src/components/MenuPanel/MenuPanel.js
src/icons/IconArrow.js

MenuPanel: add toggle animation to show/hide system apps

---

src/components/SignerPanel/SignerPanel.js

Requires an upgrade to aragon.js with https://github.com/aragon/aragon.js/pull/279.

fix: update for @aragon/wrapper api cleanup

---

src/components/MenuPanel/MenuPanelFooter.js

fix: align connect account with preferences button

---

src/components/AppIcon/assets/app-home.svg

Update home icon

---

src/components/Activity/ActivityItem.js
src/web3-utils.js

Activity Panel: shorten addresses + fix layout

---

src/Wrapper.js
src/apps/AppCenter/AppCenter.js
src/apps/AppCenter/UpgradeAppPanel.js
src/aragonos-utils.js
src/components/SignerPanel/ActionPathsContent.js
src/web3-utils.js

The radspec description is too technical for normal users right now, and will require an `@aragon/wrapper` upgrade to prettify it (see https://github.com/aragon/aragon.js/pull/284 for how it renders).

App Center: upgrade app

---

src/apps/AppCenter/InstalledApps/AppContent.js

App Center: align icon, name, and author in content

---

src/components/Upgrade/UpgradeOrganizationPanel.js

Note: aragonpm.eth points to https://etherscan.io/address/aragonpm.eth
<p align=center><img src=https://user-images.githubusercontent.com/36158/56312072-b0523900-614f-11e9-812d-280406342aa6.png width=400>

Upgrade org panel: fix links

---

package.json

Allows rinkeby users to randomly get test DAI.

feat: upgrade @aragon/templates-tokens

---

src/apps/Permissions/AppCard.js

Permissions: fix the cards layout with long names

---

src/components/SignerPanel/SignerPanel.js
src/contexts/ActivityContext.js

I believe these fields / parameters aren't used anymore.

fix(Activity Panel): remove unused parameters when adding activity

---

src/components/MenuPanel/MenuPanelFooter.js

MenuPanelFooter: wrap container to available width

---

src/aragonjs-wrapper.js
src/worker-utils.js

Improves the first load performance when starting the WebWorkers.

Apps: load WebWorkers via local object URL

---

src/components/MenuPanel/MenuPanelAppGroup.js
src/components/MenuPanel/MenuPanelInstance.js
src/hooks.js

https://www.loom.com/share/3a7bc701fb7c46309c3e60a813bb4a99
```sh
cd aragon
git fetch
git checkout feature/custom-menu-instance-labels
```
Add some labels to app instances via the Settings app

Custom menu instance labels

---

package.json

Adds pretransaction support for forwarders requiring fees.

Upgrade @aragon/wrapper

---

scripts/start

Fix npm start script

---

src/components/GlobalPreferences/CustomLabels/LocalIdentities.js

Cant merge until [Global settings PR](https://github.com/aragon/aragon/pull/861) is merged on master, and aragon-ui`s [newstyle PR](https://github.com/aragon/aragon-ui/pull/391) is merged on master

Fix on spacing on global settings buttons

---

src/known-organizations/index.js

Fix BrightID's org name

---

src/App.js
src/components/HelpScoutBeacon/HelpScoutBeacon.js

These changes also include the new help color for the help scout button:

Help Scout opt-out fix

---

src/components/GlobalPreferences/CustomLabels/EmptyFilteredIdentities.js
src/components/GlobalPreferences/CustomLabels/EmptyIdentities.js
src/components/GlobalPreferences/CustomLabels/Import.js
src/components/GlobalPreferences/CustomLabels/LocalIdentities.js
src/components/GlobalPreferences/CustomLabels/RemoveModal.js
src/components/GlobalPreferences/CustomLabels/ShareModal.js
src/components/GlobalPreferences/CustomLabels/useIdentitiesActions.js
src/components/GlobalPreferences/CustomLabels/useSelectIdentities.js
src/components/GlobalPreferences/GlobalPreferences.js
src/components/GlobalPreferences/HelpAndFeedback/HelpAndFeedback.js
src/components/GlobalPreferences/Network/Network.js
src/components/GlobalPreferences/SharedIdentities/useSharedLink.js
src/components/HelpScoutBeacon/HelpScoutBeacon.js
src/components/IdentityBadge/LocalIdentityBadge.js

Some things noticed during the review, mostly bringing new styling utilities to move the layout closer to the designs and small code clean ups.
Easiest to review commit-by-commit.

Preferences polish

---

src/Wrapper.js
src/apps/Organization/Organization.js
src/apps/Permissions/Permissions.js
src/components/App/AppInternal.js
src/components/OrgView/OrgView.js
src/index.js
src/worker/SandboxedWorker.js

- Add `AppInternal`.
- Also hide the border of `SandboxedWorker`.
- Disable `scrollView` on `Main`.

Manage internal apps layout logic in a dedicated component

---

package.json
src/apps/AppCenter/AppCard.js
src/components/GlobalPreferences/CustomLabels/EmptyIdentities.js
src/components/IdentityBadge/LocalIdentityBadge.js
src/components/IdentityBadge/LocalIdentityPopoverTitle.js
src/components/SignerPanel/ActionPathsContent.js

Updates the deprecated props and updates the LocalIdentityBadge's popover action to include an icon.
**TODO**

Badges: update for aragonUI

---

src/components/IdentityBadge/LocalIdentityBadge.js

IdentityBadge: fix button alignment

---

HACKS.md
package.json

Remove unnecessary hacks from prior web3 versions

---

src/environment.js

These changes go together with: https://github.com/aragon/aragon-apps/pull/943
An organization with `Agent` installed is required. Suggestion: `006`

Add Agent data to environment

---

src/components/GlobalPreferences/Notifications/ManageNotifications.js
src/components/GlobalPreferences/Notifications/NotificationModals.js
src/components/GlobalPreferences/Notifications/Notifications.js
src/components/GlobalPreferences/Notifications/NotificationsInfoBox.js
src/components/GlobalPreferences/Notifications/NotificationsLogin.js
src/components/GlobalPreferences/Notifications/NotificationsVerify.js
src/components/GlobalPreferences/Notifications/SubscriptionFilters.js
src/components/GlobalPreferences/Notifications/SubscriptionsForm.js
src/components/GlobalPreferences/Notifications/SubscriptionsTable.js

Some small and easy improvements and adjustments while reviewing https://github.com/aragon/aragon/pull/904#discussion_r321997876.

Preferences: polish notifications

---

src/components/GlobalPreferences/CustomLabels/LocalIdentities.js
src/components/GlobalPreferences/GlobalPreferences.js

- Header padding
- Local identities: List size and position

Global preferences fixes

---

src/components/SignerPanel/SignerPanel.js

Fixes support for Frame v0.2 (https://github.com/aragonone/product/issues/133#issuecomment-528622692)

SignerPanel: sanitize transaction object

---

src/GlobalErrorHandler.js
src/components/GlobalPreferences/HelpAndFeedback/HelpAndFeedback.js

- GlobalErrorHandler: fix logo dimensions
- HelpAndFeedback center title (mobile)

Global error and Help and feedback fixes

---

src/components/GlobalPreferences/Notifications/NotificationsLogin.js

Fixes and issue in the Design review 0.8 II list.

Changed email notifications copies

---

src/components/GlobalPreferences/Notifications/NotificationsInfoBox.js
src/templates/company/index.js
src/templates/membership/index.js
src/templates/reputation/index.js

This PR includes
- Fix BN maths for the templates instantiation to make sure we always work with BN instances
- Fix templates code links
- Fix `NotificationsInfoBox` prop types linting error

Fix onboarding bignumber usage

---

src/templates/company/index.js
src/templates/kit/ClaimDomain.js
src/templates/kit/Tokens.js
src/templates/kit/Voting.js
src/templates/membership/index.js
src/templates/reputation/index.js

:see_no_evil: :see_no_evil: :see_no_evil:

Fix the "?" redirection on Chrome

---

src/apps/Permissions/Home/Home.js
src/apps/Permissions/ManageRolePanel.js
src/apps/Permissions/Permissions.js
src/apps/Permissions/PermissionsView.js
src/components/LocalLabelAppBadge/LocalLabelAppBadge.js
src/contexts/PermissionsContext.js
src/permissions.js

Permissions: use AppBadge

---

src/components/Error/DAONotFoundError.js

DAO not found: fix copy spacing

---

src/components/Activity/ActivityItem.js

Activity: allow item text to be two lines

---

src/components/ErrorModal/ErrorModal.js
src/onboarding2/Create/Create.js

@sohkai It restarts from the first signature whenever it fails. Do you think it should resume from the failed one?

Onboarding: error modal

---

src/components/HelpScoutBeacon/HelpScoutBeacon.js
src/onboarding2/Configure/ConfigureTemplateScreens.js
src/templates/kit/PrevNextFooter.js

- Adds some bottom padding during configuration for the HelpScout beacon
- Displays the back button during configuration
- Update HelpScout's positioning on mobile to be 2GU from edge

Onboarding: polish

---

src/known-organizations/index.js

Onboarding: fix suggestions not loading descriptions on mainnet

---

src/apps/Permissions/AppPermissions.js
src/components/GlobalPreferences/Notifications/SubscriptionsTable.js

Ref: https://github.com/aragon/aragon-ui/pull/594#pullrequestreview-288252212

Memoize deps for DataView

---

src/onboarding2/Configure/ConfigureTemplateScreens.js
src/onboarding2/Create/Create.js
src/onboarding2/Onboarding/Onboarding.js
src/onboarding2/Welcome/Welcome.js

Ensure they don’t get rerendered [on scroll](https://github.com/aragon/aragon/blob/master/src/onboarding2/Onboarding/Onboarding.js#L184).

Onboarding: memoize Create + Welcome

---

src/components/GlobalPreferences/Notifications/SubscriptionsForm.js

Normal state color was ok, but disabled state had not been set.

SubscriptionsForm: update disabled icon color

---

src/onboarding/Create/Create.js
src/onboarding/Templates/TemplateDetails.js
src/onboarding/Templates/Templates.js
src/prop-types.js
src/templates/company/index.js
src/templates/membership/index.js
src/templates/reputation/index.js

Following the change made by https://github.com/aragon/aragon/pull/1086

Templates: rename “modules” to “apps”

---

package.json
src/templates/fundraising/components/BoardInfo.js
src/templates/fundraising/components/ShareInfo.js
src/templates/fundraising/index.js
src/templates/kit/screens/FundraisingScreen.js

Mostly I've had to udpate some of the inputs fields, make sure each parameter was compliant with our template interface, and implement the fucking maths to derive the actuals parameters from the user passed ones. This last part was the trickiest one. It's hard to test it generally but i've tested it over several configurations and every works well ! 💪 
A couple of last things need to be polished. Could you guys @deam and @bpierre have a look cause I'm really lame at frontend / React things.
**Handle floats for price**
Ideally the presale price and starting price should be float [if someone wants a starting price of 1.5DAI/share let's say]. The actual implementations filters non integer in the frontend. I've tired to implement my own here: …

Template fundraising

---

src/onboarding/Deployment/DeploymentStepsPanel.js

Fixes https://github.com/aragon/aragon/issues/1065.

Onboarding: remove information about waiting for transactions to mine when deployment is finished

---

src/App.js
src/GlobalErrorHandler.js
src/components/Error/DAONotFoundError.js
src/components/Error/ErrorScreen.js
src/components/Error/GenericError.js
src/components/HomeButton/HomeButton.js
src/index.js
src/onboarding/Onboarding/Onboarding.js
src/onboarding/Onboarding/OnboardingTopBar.js

- Fix the error message breaking its container with long errors.
- Make the error work on small views.
- Use the right colors from the theme.
- Use black (#000000) shadows.
- Align the structure of the two error components.
- Change the button label from “restart the app” to “reload”, to make it
consistent with the description text.
- Move Main above GlobalErrorHandler so we can use useViewport().

Error screen: various fixes

---

src/onboarding/Templates/TemplateCard.js
src/onboarding/Templates/TemplateDetails.js

(Slightly older version of the demo: https://imgur.com/a/RU9WEkr).
This allows the template's detail card to be opened, so the user can read more about the template, but does not let them proceed with the actual onboarding.

Templates: allow disabled, 'coming soon' templates to be opened

---

package.json
src/onboarding/Templates/TemplateCard.js

And also fix some linting errors :)

chore: update @aragon/wrapper

---

src/templates/open-enterprise/index.js

Open Enterprise's apps and templates have now been published on mainnet.

Templates: enable Open Enterprise

---

src/apps/AppCenter/AppCenter.js
src/apps/AppCenter/DiscoverApps/discover-apps-data.js

- "App Center" is Title Cased in the side bar, it should be in the header too
- Update Agent app copy

Copy updates

---

src/components/SignerPanel/ActionPathsContent.js

See https://github.com/aragon/aragon/issues/1172.
cc @lkngtn @stellarmagnet

SignerPanel: soften copy for external actions to be less harsh

---

src/onboarding/Deployment/DeploymentStepsPanel.js

Onboarding: update info component

---

src/apps/Permissions/AppPermissions.js

Add bar with back button when an app without permissions is displayed

---

src/Wrapper.js
src/prop-types.js

Small updates to the shape we're expecting from apps.
Notably, some of the prop types that were previously marked as required should not be as they're loaded from the app's content.

Update expected proptype shape of loaded applications

---

.gitignore

chore: update gitignore for new public/ production build folder

---

src/templates/fundraising/index.js

Onboarding: temporarily disable fundraising

---

src/templates/dandelion/config/helpers/getBlockTime.js
src/templates/dandelion/config/screens/DandelionVotingScreen.js
src/templates/dandelion/config/screens/LockScreen.js

Onboarding: update Dandelion copy

---

src/templates/index.js

Keep Fundraising in first three as a relatively new template.

Onboarding: update order of templates

---

.gitignore

As added by the new now configuration (they use this folder to configure the Zeit project to deploy to).

Add .now to ignored list

---

src/components/GlobalPreferences/GlobalPreferences.js
src/components/LocalIdentityModal/LocalIdentityModal.js
src/onboarding/CircleGraph.js

Fix the custom labels modal when the dark theme is enabled.

Theme: remove hardcoded colors

---

package.json
yarn.lock

See https://github.com/aragon/use-wallet/pull/24 and https://github.com/NoahZinsmeister/web3-react/pull/71.

Update use-wallet to fix a connection error with MetaMask mobile

---

src/onboarding/Welcome/Welcome.js
src/onboarding/validate-requirements.js

Fixes https://github.com/aragon/aragon/issues/1325
Let users create an organization if the provider doesn’t share the balance.

Org creation requirements: remove unknown balance

---

package.json
yarn.lock

Fixes an issue with some providers response format.
See https://github.com/aragon/use-wallet/pull/25

Update use-wallet to 0.4.4

---

src/wallet.js

Fixes #1320 . Turns out it was a small mistake!

Providers: Use correct function for detecting the used provider

---

src/Wrapper.js
src/apps/Organization/Organization.js

Try it out with your favourite orgs now :).

Organization: add Tenderly import

---

CONTRIBUTING.md
README.md

- Update Aragon Chat links to Spectrum

chore: update Aragon chat links

---

README.md

README: update organizations

---

src/onboarding/Onboarding/Onboarding.js
src/onboarding/Templates/TemplateCard.js
src/onboarding/Templates/TemplateDetails.js
src/templates/dandelion/index.js
src/templates/dictatorship/components/DictatorScreen.js
src/templates/dictatorship/header.svg
src/templates/dictatorship/icon.svg
src/templates/dictatorship/index.js
src/templates/index.js
src/templates/kit/screens/TokensScreen.js

THE PEOPLE HAVE SPOKEN!
TRUE PMF IS WITHIN GRASP!
DON'T ASK, JUST DO!

2020-04-01

---

src/apps/AppCenter/AppCenter.js

AppCenter: crashing fix due to not having the state loaded from chain yet

---

src/apps/AppCenter/AppCard.js

App Center:  keep descriptions to three lines

---

src/apps/AppCenter/InstalledApps/RepoVersions.js
src/date-utils.js

App center: Change release date format

---

src/components/AppInstanceLabel.js
src/components/GlobalPreferences/CustomLabels/RemoveModal.js
src/components/GlobalPreferences/CustomLabels/ShareModal.js
src/components/GlobalPreferences/GlobalPreferences.js
src/components/GlobalPreferences/Notifications/NotificationModals.js
src/components/GlobalPreferences/SharedIdentities/SharedIdentities.js
src/components/HelpScoutBeacon/HelpScoutBeacon.js
src/components/LocalIdentityModal/LocalIdentityModal.js

Spring cleaning 🌸, closing #1186 .
> They are dirty, stale, without consistency. But you. You will be cleaner. **Code and push, until it is merged!**  [cue music](https://www.youtube.com/watch?v=zZMg9ryeWOw&t=123s)

Styling: Migrate breakpoint to use-viewport wherever possible

---

src/apps/Console/ConsoleFeedback.js

Spring cleaning 🌸! closes #1296 .
> So, Pull Slayer, you walk eternally through the issue realms, standing against stale issues where all others falter. May your thirst for Github contributions never quench, may the coffee on your cup never run out, and may we never leave PRs go stale again.
Adds a new flow for the act command, matching the style used for the `exec` (and hidden install) command. Screenshots for easy inspection:
Selecting an Agent:
Using the agent instance:
No agent installed:

Console: add new flow for act command

---

src/apps/Permissions/Home/AllPermissions.js
src/apps/Permissions/PermissionsView.js

PermissionsApp: Manage pagination in a controlled way

---

package.json
src/components/Activity/TimeTag.js
src/components/GlobalPreferences/CustomLabels/useIdentitiesActions.js
src/date-utils.js

Replace `date-fns` for `day.js`

---

src/templates/dandelion/config/screens/DandelionVotingScreen.js
src/templates/dandelion/config/screens/LockScreen.js
src/templates/fundraising/components/Council.js
src/templates/fundraising/components/Holders.js
src/templates/kit/screens/DotVotingScreen.js
src/templates/kit/screens/FundraisingScreen.js
src/templates/kit/screens/TokensScreen.js
src/templates/kit/screens/VotingScreen.js

See https://github.com/aragon/aragon-apps/pull/1117.
Aligns all the onboarding hints' titles and copy to be similar in style.

Onboarding: align hint titles and copy

---

src/apps/AppCenter/InstalledApps/AppContent.js

Upgrade App -> Upgrade app
We do not use title casing in buttons.

Fix title casing

---

src/components/IdentityBadge/IdentityBadgeWithNetwork.js
src/components/IdentityManager/IdentityManager.js
src/components/LocalLabelAppBadge/LocalLabelAppBadge.js
src/hooks.js

Fixes https://github.com/aragon/aragon/issues/1423

Properly update the app & identity badge custom labels

---

package.json
src/components/Error/GenericError.js
src/components/MenuPanel/MenuPanel.js
yarn.lock

Requires https://github.com/aragon/aragon-ui/pull/729

Use Details

---

README.md

Notes / markets some useful dependencies we currently use.
Any others we should note?

README: note useful dependencies for others

---

src/components/FeedbackIndicator/FeedbackIndicator.js
src/components/SignerPanel/SigningStatus.js

Noticed the wrong colour on this text. I've tweaked it to improve the contrast.

Signing Indicator: Text contrast

---

src/apps/Organization/Organization.js
src/components/AccountModule/AccountModuleConnectingScreen.js
src/components/ConnectModal/ConnectModal.js
src/components/SignerPanel/ActionPathsContent.js
src/components/SignerPanel/SignerPanel.js
src/components/SignerPanel/SigningStatus.js
src/components/SignerPanel/Web3Errors.js
src/components/SignerPanel/signer-statuses.js
src/ethereum-providers/index.js

Updates some missed copy from the last major update to the Account module. I think this should be them all :).

Account: update instances of 'Ethereum provider' to wallet terminology

---

src/components/AccountModule/connection-hooks.js

Small improvement over #1474 for better variable naming.

AccountModule: Add better naming to default connection hook variables

---

src/components/SigningModal/TransactionJourney.js

Address https://github.com/aragon/aragon/pull/1452#discussion_r449460154
These now handle fallbacks and all other goodness provided by `<AppIcon/>`

Signing modal: Render icons in journey via app data

---

src/components/SigningModal/SignMessageFlow.js
src/components/SigningModal/SignTransactionFlow/SignTransactionFlow.js
src/components/SigningModal/Web3Errors.js
src/components/SigningModal/useWalletError.js

Builds on https://github.com/aragon/aragon/pull/1502
Simple port of `Web3Errors` from existing `SignerPanel` via hook. None of the error components have been modified.

Signing modal: 2 – Port Web3Errors from SignerPanel

---

src/known-organizations/index.js

Tiny edit for "name" field on index.js

---

src/components/Migrate/MigrateBanner.js
src/onboarding/validate-requirements.js

@Rekard0 , I changed the animation to use opacity instead of height as the animation does not always work with variable height.

DAO-25 banner height and minor text fix

---

src/App.js
src/check-domain.js
src/client-web3.js
src/components/AccountModule/connection-hooks.js
src/components/AccountModule/useClientBlockNumber.js
src/index.js
src/onboarding/Create/Create.js
src/web3-utils.js

This fixes the error due to bad web3 provider handle and also fixes the slow down in looking up ens name due to too many open web sockets.

DAO-112 Open organization error

---

src/App.js

refreshes the DAO on network change

DAO-80 network reactive dapp

---

src/analytics.js
src/check-domain.js
src/onboarding/Create/Create.js
src/templates/kit/screens/ReviewScreen.js

- track analytics event :
TEMPLATE_SELECTED
WALLET_DISCONNECTED
DAO_CREATEBTN_CLICKED
DAO_CREATED
DAO_CREATIONFAILED

add analytics events DAO-97

---

src/App.js
src/onboarding/Onboarding/Onboarding.js

@novaknole , without the fix the gas estimation below would silently not work (no estimation), but, create dao still work.  I'm debating if we should keep the gas estimation as the gas estimate may be too high now because of EIP1559.
https://github.com/aragon/client/blob/master/src/onboarding/Create/Create.js#L432-L434
Initially noticed this bug because the following line in ActivityContext logging error in console log.. from testing the govern dao migration...
https://github.com/aragon/client/blob/master/src/contexts/ActivityContext.js#L96

DAO-202: fix undefined web3 error

---

src/App.js
src/analytics.js
src/onboarding/Templates/TemplateDetails.js
src/templates/kit/screens/ReviewScreen.js

- Migrate anlaytics to Rudderstack
- add network to events

Feature/ DAO-126 and DAO-155

---

src/templates/kit/PercentageField.js

- allow backspace to delete the last digit

Bug / DAO-196

---

src/components/Carousel/Carousel.js
src/network-config.js

- Carousel behaviour correction

Feature/ DAO-230

---

package.json
yarn.lock

Update use-wallet to use v0.10.0 instead of multichain branch

updated useWallet to 0.10.0

---

package.json
yarn.lock

All the changes are made in radspec and wrapper, this is just to make client use those libraries.

DAO-240: Client finance app currency issue

---

src/contexts/wallet.js

This PR adds the following functionality:
- On any network change (either through the network changing modal when a user is disconnected, or through the wallet if a user is connected), the new network is stored in local storage under the variable `last-network`.
- When a user (re-)loads the webapp, the value of `last-network` is retrieved from local storage. The webapp is then loaded with respect to that network. 
- If the value is undefined, `main` is used as default value

Store last network DAO-312

---

src/network-config.js
src/templates/dandelion/config/helpers/getBlockTime.js

@githubdoramon not sure why i didn't create a PR for this which was requested by you a while back.. and they are needed by the dandelion dao template. Cannot create Dandelion template without the Dai address.

DAO-444: add dai address

---

src/network-config.js

This address does have liquidity on Rinkeby Uniswap unlike the former one

Changed the DAI address to the official Rinkeby Compound DAI address

---

.github/workflows/deploy_develop.yml
.github/workflows/deploy_prod.yml

Same fix as in #1740 but for the develop branch

fix: replaces faulty fleek url after build

---

src/index.html

This is a patch to remove the helpscout code and install the hubspot code to track and support Aragon Client users

Dtech patch 1 - helpscout to hubspot

---

arapp.json

fix: changes goerli ENS registry to the correct address
