src/App.js
Allow app names to have upper case, numbers, and `_` (`\w` matches `[a-zA-Z0-9_]`).
@onbjerg @izqui do we have a spec on what apps (and their instances) can be named?
=> App: allow wider range of app names

src/App.js, src/components/Home/Home.js, src/components/MenuPanel/MenuPanel.js, src/components/MenuPanel/MenuPanelAppGroup.js
Small refactor:
- App only passes `handleNavigation()` to any component that _could_ control the wrapper's navigation
- Usages of ids for apps or instances are made explicit
=> Unify MenuPanel and Home's navigation API

src/components/App/AppIFrame.js
So... apparently changing an iframe's src adds an entry to the browser's history. That means we used to have a lot of duplicate entries, making the back button pretty much useless.
To get around this, we employ a hack by [only manipulating the iframe's src when it's removed from the DOM](https://github.com/aragon/aragon/compare/iframe-fix-history?expand=1#diff-60f77f8e53f30f5936a4866cc7257f42R74). AFAIK, since this is done synchronously, and the changes don't clash with any React-controlled attributes, React doesn't care.
I also added src caching for the iframe, so that if you navigate away and then back to the same app, it doesn't reload (a number of progress bar tweaks were also necessary for this).
=> AppIFrame: cache src and fix duplicate browser history entries

src/components/MenuPanel/MenuPanel.js
Prevents the MenuPanel shadow to appear lighter if an app uses a dark overlay:
=> MenuPanel shadow: use black as a base

src/components/App/AppIFrame.js
Oops... totally forgot styled components need to use `innerRef` the first time.
=> AppIFrame: use innerRef rather than findDOMNode to get the actual iframe

src/App.js
When we start needing the current app instance in more places (e.g. #101), it seemed unnecessary to keep calculating it rather than caching it in the state during navigation.
=> App: cache appInstance in state

src/components/App/AppIFrame.js
Adds some functionality to `AppIFrame` to send and receive messages from the parent.
Due to how aragon-js handles message passing, `sendMessage()` may not be used in the future,  but I've included it in case we find ourselves needing to manually pass some messages in the future.
=> AppIFrame: handle message passing

src/components/MenuPanel/MenuPanel.js
We're not using this yet. Let's re-enable it once we do.
=> Hide wallet icon

src/App.js, src/components/SignerPanel/SignerPanelContent.js, src/demo-state.js
Fixes #64.
Requires https://github.com/aragon/aragon-ui/pull/116, https://github.com/aragon/aragon-ui/pull/117, https://github.com/aragon/aragon-ui/pull/118 (merged branch: https://github.com/aragon/aragon-ui/tree/signer-ui-merged).
Not yet hooked up to a web3 instance, but I can do that after the aragon.js integration (🤞this should just be hooking up the browser-provided web3 provider and then a `.sendTransaction()`).
Currently expects the following data format (see [demo state](https://github.com/aragon/aragon/commit/a374171f71379bbc8be473446baa76ff0c4b0c36#diff-897cda2bfa1893ce533ee6ee00aff957R175)):
```
intent: {
description: description of action's intent, usually in the form of "perform <action> to"
to: contract addr,
tx: [optional] if provided, the action is assumed to be directly …
```
=> Add Signer panel UI

src/components/MenuPanel/MenuPanelAppGroup.js
`proxyAddress` will absolutely, definitely, 101% always, be unique (or we're all screwed).
=> Use proxyAddress for app identity

README.md
The previous link of logo is missing https://github.com/aragonone/issues/blob/master/logo.png
Use logo in `src/components/MenuPanel/assets/logo.svg` instead
=> fix logo path in README

package.json
According to https://github.com/aragon/aragon/blob/master/LICENSE aragon/aragon use AGPLv3
Since `AGPLv3` has some different attribute with `GPLv3`, we should show the right license in npm
=> correct the license to AGPLv3

src/aragonjs-wrapper.js
Oops, let's pretend I knew that<sup>1</sup> could happen.
<sup>1</sup>`await` gives up the current context, so if the `apps` stream emits faster than we can fetch the worker scripts, it's possible more than one context could be on their way to starting worker scripts for the apps.
=> Check to make sure an app doesn't have a running worker instance before starting one

src/App.js, src/aragonjs-wrapper.js
Requires https://github.com/aragon/aragon.js/pull/93.
Sets the available accounts on the aragon.js wrapper.
=> Set accounts on aragon.js

src/App.js, src/aragonjs-wrapper.js
We shouldn't use `wrapper.setAccount()` more than we have to; its subscribers will be constantly getting executed.
Also fixes a [equality check](https://github.com/aragon/aragon/pull/148/files#diff-c1957ab402163ee0da348f170f242479R103) due to web3 using BN for the balance (but for nothing else??? wtf?)
=> Separate account and balance into two callbacks

.travis.yml
Currently failing because of https://github.com/ipfs/js-ipfs-api/pull/697.
=> Travis: add build script to CI

src/aragonjs-wrapper.js
We're filtering out all the apps because it filters for `short_url`, but it's actually called `start_url`.
Furthermore, I think we should default to `/index.html` as opposed to filtering out the app.
=> Default `start_url` to `index.html`

package.json, scripts/build-analyze.js
It creates a page to vizualize the size of each dependency, and also generates a `build/stats.json` file that can be used by different viewers like [webpack-visualizer](https://chrisbateman.github.io/webpack-visualizer/).
=> Add a build:analyze script

src/App.js, src/aragonjs-wrapper.js, src/errors.js
Start using generic errors that can be used in the app.
An error type can be tested using `instanceof`, e.g. `err instanceof InvalidAddress`.
=> Add generic errors

src/Wrapper.js, src/components/SignerPanel/SignerPanelContent.js, src/web3-utils.js
Fixes #183, requires #175.
Tries to substitute a transaction's `to` address with an installed app's name, if possible.
Also modifies the signer panel's text to fit a little better with the current descriptions (now always in the form of `... perform "<description>" on ...`).
=> Signer: parse addresses to installed app name

src/components/MenuPanel/MenuPanelAppGroup.js
soon -> SOON
Purely visual preference. @bpierre @jounih opinions?
=> Capitalize SOON in 'coming soon' apps

src/apps/Settings/Settings.js, src/environment.js, src/local-settings.js
Temporary solution to #113 and #114.
Allows you to use `REACT_APP_DEFAULT_ETH_NODE` and `REACT_APP_IPFS_GATEWAY` to control the nodes the wrapper connects to. Also exposes inputs in the Settings app to change them (however, see below).
Example CLI usage:
```
REACT_APP_DEFAULT_ETH_NODE=ws://localhost:8545 REACT_APP_IPFS_GATEWAY=localhost:8080 yarn start
```
--------------
--------------
The Settings app currently requires at least a connection to a ETH node to load, which means the UI fields aren't super useful (ideally you could access them even without any DAO loading; they're more of a "client" setting than "org" setting).
=> Add ability to change ethereum and IPFS node

package.json, src/aragonjs-wrapper.js, src/components/App/AppIFrame.js, src/components/MenuPanel/MenuPanel.js, src/utils.js
Correctly factor in `start_url` for the app's source location.
Also forces the `start_url` and `script` assets to be loaded relative to the resolved base url of the app (either an ipfs gateway or our own bridge).
=> Refactor app loading to correctly take into account start_url and relative asset locations

package.json, scripts/dev-launch.sh, src/local-settings.js
Fixes #239.
Refactors the local configuration's constants for a simpler API to add more options, and uses `URL()` instead of a regex for parsing urls.
Also includes a quality of life local development script, `start:local`, that will set all the local options to their defaults. `REACT_APP_ENS_REGISTRY_ADDRESS` is still required as it'll most likely change between users.
@izqui `start:local` may also be useful for simplifying the dev tools.
=> Improvements to local configuration settings

package.json
Upgrading should allow us to avoid weird issues where web3.js was passing events back to the error handler rather than event handler.
=> Upgrade @aragon/wrapper to 2.0.0-beta.35

README.md, scripts/dev-launch.sh, src/environment.js, src/local-settings.js, src/worker-utils.js
Allows users to select where they'd like to load apps' frontends from.
Using `ipfs` does not work right now with a non-local gateway due to security warnings.
=> Add asset bridge environment option

src/Wrapper.js
Adding `addressesEqual` comparison everywhere to ensure that checks
pass even if only one of the compared addresses are not checksummed.
=> Fix issue with cloudflare non-checksummed addresses

package.json
Note that AGPL-3.0 by itself is considered deprecated: https://spdx.org/licenses/.
=> Fix package.json's AGPL license

src/components/App/AppIFrame.js
Fixes app navigation when you're already on another instance of that app.
cc @bpierre
=> AppIFrame: navigate when it's the same app but a different instance

src/Wrapper.js
The transaction that's provided is the same as the one in `transactionBag`.
cc @bpierre
=> Wrapper: use the provided tx rather than grabbing it from the transactionBag when sending a tx to sign

src/environment.js
Looks like cloudflare doesn't support certs down to `mainnet.survey.aragonpm.com`, so we'll downgrade to HTTP for now.
=> Downgrade mainnet survey to http due to cloudflare

HACKS.md, package.json
Pinning underscore.js dedupes `web3.js`'s pinned version :cry:.
Also adds a HACKS.md to keep track of some of these...
=> Add HACKS.md and pin underscore.js

src/onboarding/templates/multisig/ConfigureMultisigAddresses.js
`DropDown` now requires a string for its `items`.
=> Fix DropDown in multisig onboarding

package.json, src/permissions.js
See https://github.com/aragon/aragon.js/pull/137 (requires releasing `@aragon/wrapper` before merging this)
This also makes the manager address accessible so it can be shown in the UI to denote the entity that can grant and revoke the permission!
I don't think this needs to be modified anywhere else, but PTAL @bpierre :)
=> Support new aragon.js permissions data structure

src/Wrapper.js
Fixes cases where no path is found:
Fixes #260.
=> Fix empty list of transaction paths

src/apps/Permissions/Screen.js
Before this change, the transition had to end before the screen could be interacted by the user.
=> Permissions: make the entering screen active

package.json
This is required to serve the dapp from URLs like `http://localhost:8080/ipfs/{hash}`, which are the default ones that the IPFS daemon has.
=> Using --public-url so it works with plain IPFS

src/App.js
#372 was missing this in order for aragon-ui resources to properly load.
=> Use relative URL for aragon-ui publicUrl

src/apps/Permissions/Permissions.js, src/contexts/PermissionsContext.js, src/permissions.js, src/web3-utils.js
Loosens the strictness on comparing address strings.
I think it's mostly the `Kernel` that's affected by this, as we get it from the URL or ENS, but still nice to have until we find it's a large performance problem.
Before:
After:
=> Permissions: fix address equality checks to be less strict on checksums

src/apps/Permissions/Home/BrowseByApp.js
`appId` is not a unique identifier for apps in a DAO as multiple instances of the same app can be installed.
=> Permissions: Use proxyAddress for AppCard key instead of appId

src/permissions.js
When clicking on an app using “Browse by apps”, the permissions granted to this app were not displayed, because apps are using non-checksum addresses, while permissions are using checksum addresses.
All app addresses are now lowercase.
=> Always display the permissions granted to apps

README.md, src/environment.js
Maintaining the asset bridge to with `apm-serve` makes the app more centralized than it could be (when using the CLI with Kits we are already running apps directly from an IPFS gateway without problem) and it is going to be a pain to maintain with multiple environments.
Currently having some issues when running with Rinkeby settings ~because [the manifest](http://voting.aragonpm.com/manifest.json) of the apps uses absolute URLs to the resources. I think updating the manifest should be enough for the apps that have been published recently, but we may have to redeploy them all.~ Edit: The issue is actually with the resources that get loaded inside the frontend, the wrapper already removes the starting slash from the manifest values if found.
> GET https://ipfs.io/static/js/main.6b4a1a10.js …
=> Remove apm-serve asset bridge

package.json, scripts/build, src/index.js
Rudimentary cache busting based on Aragon Core versions.
Let's assume for now that we only make breaking changes to the cache structure on minor version increments (for our own apps). Ideally this would be done in each app instead.
=> Purge localstorage if user's last session was not on the current version

src/components/MenuPanel/MenuPanelAppsLoader.js
Easiest solution for now, until we get [transient props](https://github.com/styled-components/styled-components/pull/2093).
=> Fix a styled-component warning (prop being set as DOM node attribute)

src/onboarding/Sign.js
=> Onboarding: avoid bottom text in signing screen from being cut off in smaller screens

src/apps/Permissions/AppRoles.js, src/apps/Permissions/EntitySelector.js, src/permissions.js, src/web3-utils.js
With `aragonOS@4` we have have the standard notion of a "burned" permission manager, i.e. a permission with its manager thrown away so that it's forever frozen (from the state it was in when it was "burned").
This fixes the app crashing when no `allowedEntities` exist, but the manager does (likely because the permission's been completely thrown away), and also adds detection for these managers. I've opted to use `Discarded` as the label name, and think it doesn't look too out of place:
=> Burned permissions

src/Wrapper.js, src/components/SignerPanel/SignerPanelContent.js
Show the description of the actual transaction path's intent (ie. its final action), rather than what the first action would do.
Right now, the description would basically always say "makes a new vote", whereas it would be nicer to show the final transaction's description (e.g. "mint tokens" or "transfer funds") since that's what the user actually wanted to accomplish.
The description looks something like this:
=> Show final intent in signing panel

src/App.js, src/aragonjs-wrapper.js, src/onboarding/Onboarding.js, src/onboarding/Start.js, src/web3-utils.js
Fixes https://github.com/aragon/aragon/issues/440
When calling getBalance(), it was possible to sometimes get another value than an big integer as a string.
Having `null` as a result, and passing it to the BN.js constructor, [could lead to an infinite loop](https://github.com/indutny/bn.js/issues/186).
To prevent this issue to happen again:
- In the app, `balance` is now always represented by a BN.js instance. To represent an unknown balance, `new BN(-1)` is now used rather than `null`.
- The result of getbalance() is now filtered to ensure that we are passing an integer to BN.js. Otherwise, we pass `"-1"`.
=> Fix an onboarding crash happening with specific web3 provider setups

.babelrc
We already [declare the browerslist in a cross-tool compatible way in the package.json](https://github.com/aragon/aragon/blob/master/package.json#L107).
=> chore: unify and update browserslist

.babelrc
Hmm, not sure how we got away with not including this up to now 🤔
=> chore: add preset-react to babel config

src/utils.js
Will later be replaced by [`blockExplorerUrl`](https://github.com/aragon/aragon-ui/blob/master/src/utils/web3.js#L69).
=> fix: properly format mainnet Etherscan URLs

src/App.js, src/aragonjs-wrapper.js, src/routing.js, src/web3-utils.js
Fixes #459 and #408.
On invalid organization routes, the following error is shown (we can probably detect this better and show a nicer error state later on?):
=> Allow all ENS names and error on invalid organization routes

src/components/Error/DAONotFoundError.js
- Remove the Rinkeby warning.
- On the DAO not found screen, replace `app.aragon.org` by `/`.
=> Remove the rinkeby-specific error when a DAO is not found

src/apps/Settings/DaoSettings.js
Removed about 15 lines of code thanks to this!
Also using `IdentityBadge` has the advantage that we can abstract over Etherscan/any other Ethereum block explorer we use, and not show the user a huge _See on Etherscan_ link
=> Use IdentityBadge in Settings

src/GlobalErrorHandler.js
One of the most common reasons an app crashes is when an organization domain can not be resolved, either because it doesn’t exist or because the connection fails. Because it is handled using a a global error, everything stops working, including the routing system, and the user can’t use the back button of the browser or update the URL.
For the specific case of resolving an organization domain, the error need to be handled gracefully rather than using a fatal error (we used to have one for this case − https://github.com/aragon/aragon/pull/365). But for other cases, it would still be useful to react to URL changes, which is what this PR does (by reloading the page).
Note: another solution would be to move the router outside of the global error handler. It could also be an opportunity to …
=> Allow location hash updates after a fatal error

src/apps/Settings/DaoSettings.js
Oops, otherwise the links will always link to a mainnet block explorer.
cc @luisivan the other changes involving `IdentityBadge`s may also require this.
=> Settings: use the current network on identity badges

src/components/SignerPanel/ActionPathsContent.js
Oops 😅. Turns out this was using the wrong handler the whole time (never detected because we never show more than one transaction path).
See https://github.com/aragon/aragon-ui/blob/master/src/components/Radio/RadioListItem.js#L33.
=> SignerPanel: fix RadioList select handler

src/App.js, src/Wrapper.js, src/apps/Settings/DaoSettings.js, src/apps/Settings/Settings.js, src/onboarding/Onboarding.js, src/onboarding/Start.js
Builds on #469 
Always uses the passed down `walletWeb3` instance.
Also removes some unnecessary default props.
=> WalletWeb3: always pass down resolved instance rather than use environment's

src/apps/Apps/Apps.js
=> Responsive apps (app list)

src/App.js, src/Wrapper.js, src/apps/Apps/Apps.js, src/apps/Permissions/Permissions.js, src/apps/Settings/Settings.js, src/components/Home/Home.js, src/components/MenuPanel/MenuButton.js, src/components/MenuPanel/MenuPanel.js, src/contexts/ScreenSize.js, src/icons/IconMenu.js, src/index.html, src/onboarding/Onboarding.js
These changes include a mechanism for apps (both wrapper/local apps and iframe apps) to communicate their intention to open/close the `MenuPanel`.
Iframe apps use `postMessage` while local apps use the same interface but don't actually post any message.
There is still plenty to do but I wanted to get a couple eyes to review the proposed solution.
This [PR](https://github.com/aragon/aragon-apps/pull/606) shows how the _iframed_ apps would interact with this behavior.
=> Responsive menu panel for wrapper and iframe apps

src/apps/Settings/DaoSettings.js
These minor changes make the `IdentityBadges` render the short version for mobile.
=> Responsive settings app

src/apps/Settings/DaoSettings.js
[Reference](https://github.com/aragon/aragon/pull/548/files#r249327353)
=> DaoSettings: update var name

src/components/Etherscan/EtherscanLink.js, src/network-config.js, src/utils.js
Fix for issue #457 about start using blockExplorerUrl from aragon/ui instead of makeEtherscanBaseUrl
=> 457 block explorer url

src/apps/Permissions/AppInstanceLabel.js, src/apps/Permissions/AppPermissions.js, src/apps/Permissions/EntityPermissions.js, src/apps/Permissions/EntitySelector.js, src/apps/Permissions/NavigationItem.js, src/components/Identicon.js, src/prop-types.js
This PR adds and applies a custom proptype for testing for an ethereum address. Both an optional and `isRequired` version.
Fixes #464 
Wanted to minimize impact on repo, so decided to add in the already existing `prop-types.js` file. Let me know if you would prefer me to extract the new logic into self-contained file. I would then like to create a folder to group the new file and `prop-types.js` file together.
First PR to Aragon, yay! :tada:
=> chore: add ethereum address proptype

src/App.js, src/Wrapper.js, src/onboarding/Onboarding.js
Turns out the signer panel's `enable()` wasn't doing anything before... 🤷‍♂️.
Builds on #581 for convenience (less merge conflicts later).
Commits:
- 1757c9a: adds missing proptypes, removes defaults when proptype is declared as required
- 13a801d: alphabetically order props to `Wrapper` to make it easier to spot missing props like this in the future
- 10c8d87: add `onRequestEnable()` to `Wrapper`
=> fix: clean proptype validation and properly pass ethereum.enable() to Wrapper

src/web3-utils.js
Apparently we're not supposed to use it at all 🤷‍♂️ 
https://github.com/status-im/status-react/pull/7349#issuecomment-458194640
=> fix: disable usage of ethereumBeta

src/components/SignerPanel/ConfirmTransaction.js
It turns out aragon.js just gives us an empty array for the `path` (and therefore `undefined` for the `transaction` and its `intent`) when no paths are found (e.g. you can't invoke it).
We might want to change this in the future in aragon.js, so the intent information is kept even if no path is found, but for now this fixes the signer panel when no paths are found.
=> fix(SignerPanel): don't assume intent is always available

src/components/SignerPanel/ConfirmTransaction.js, src/components/SignerPanel/SignerPanel.js, src/onboarding/Start.js, src/provider-strings.js, src/web3-utils.js
Fixes #614 
Also fixes the detection of no injected Ethereum provider.
=> fix: instruct user to install Frame as their Ethereum provider in electron environments

src/components/SignerPanel/ActionPathsContent.js
The previous annotation forgot to include the any accounts (which have a different annotation type than addresses)
=> SignerPanel: show Any Account

src/apps/Permissions/AssignPermissionPanel.js, src/apps/Permissions/EntitySelector.js, src/apps/Permissions/ManageRolePanel.js
Fixes https://github.com/aragon/aragonOS/issues/484.
`Any account` doesn't apply to managers; trying to set a role manager to "0xff...ff" only results in it being unchangeable.
Default `EntitySelector` with this change:
=> Permissions: hide Any Account from role management selectors

src/Wrapper.js, src/apps/Settings/Settings.js, src/index.js, src/prop-types.js
Builds on #476.
aragon.js now switches to using indexedDB for its cache whenever possible, so we need to clear that as well.
=> fix: update cache refreshes

.eslintignore, src/apps/Apps/Apps.js, src/apps/Permissions/AppRoles.js, src/components/AppLayout/AppLayout.js, src/components/DeprecatedBanner/DeprecatedBanner.js, src/components/MenuPanel/MenuPanel.js, src/components/MenuPanel/OrganizationSwitcher/OrganizationSwitcher.js, src/components/ModalManager/Modal.js, src/components/ModalManager/ModalManager.js, src/components/Notifications/NotificationAlert.js, src/components/Notifications/NotificationBar.js, src/components/Notifications/NotificationHub.js, src/components/SignerPanel/SigningStatus.js, src/components/SignerPanel/signer-statuses.js, src/icons/IconKernel.js, src/onboarding/Domain.js, src/onboarding/Launch.js, src/onboarding/PrevNext.js, src/onboarding/Sign.js, src/onboarding/Start.js, src/onboarding/StepsBar.js, src/onboarding/Template.js, src/onboarding/TemplateCard.js, src/onboarding/templates.js, src/onboarding/templates/democracy/ConfigureTokenName.js, src/onboarding/templates/democracy/ConfigureVotingDefaults.js, src/onboarding/templates/multisig/ConfigureMultisigAddresses.js, src/onboarding/templates/multisig/ConfigureMultisigToken.js
Fixes #390.
Removes all the proptypes warnings:
- Ignore the `react/prop-types` rule in most of the files in `src/onboarding`. We can add them later by searching for `eslint` in the codebase, but a cleanup / refactoring of this part is needed, so it might not be worth doing it until then.
- Add prop types for everything else.
<p align=right><img width=30 src=https://user-images.githubusercontent.com/36158/53132982-d7d2be00-3571-11e9-94e0-8434d41f11c8.png></p>
=> Removes all the react/prop-types warnings

package.json, src/Wrapper.js, src/components/MenuPanel/MenuPanel.js, src/components/MenuPanel/SwipeContainer.js
=> Menu panel swipe open close

src/components/MenuPanel/MenuPanel.js
Now that `MenuPanel` is wrapped, we need to ensure that the wrapper doesn’t grow / shrink too, so that the width is always the same.
=> Fix the width of MenuPanel

package.json, src/aragonjs-wrapper.js
This upgrade should be completely transparent to aragon/aragon, since it doesn't really make use of any rxjs operators.
=> chore: upgrade @aragon/wrapper to v4.0.0-beta.1

src/aragonjs-wrapper.js
Some internal apps, like the Kernel, ACL, and EVM Scripts Registry, aren't published onto a registry yet. This avoids erroneously setting their registry tag to `' registry'`.
=> fix: avoid assigning a registry tag if app is not on a registry

src/environment.js
Was previously moving the Kernel to be below the ACL and EVMScriptRegistry (due to later alphabeticalized checks).
=> fix: always leave Kernel as first app

package.json
this prevents errors from rxjs upgrade
https://github.com/okonet/lint-staged/issues/416#issuecomment-458830064
=> chore: Upgrade lint-staged

src/Wrapper.js, src/components/MenuPanel/SwipeContainer.js
Two changes:
- Send `displayMenuButton` (`Boolean`) to the current app.
- Prevent re-mounting the children of Wrapper on resize.
=> MenuButton: send a message to the current app

.github/main.workflow
- Replicate the travis configuration in Github
- We now wait quite a while for travis builds, Github might prove to be faster
- Github Actions are nicely integrated
- We see the failed step, e.g. lint inside the PR without having to navigate away into the Travis cosmos
- https://twitter.com/alicegoldfuss/status/1098604563664420865
- https://news.ycombinator.com/item?id=19218036
=> Add github workflow for linting/building

src/components/MenuPanel/MenuPanel.js
Seems odd to have the extra margin above the actual button (easily mistakable for the app itself):
=> fix(MenuPanel): avoid clickable margin above system apps toggle

src/apps/Permissions/AppPermissions.js, src/apps/Permissions/AppRoles.js, src/apps/Permissions/Home/EntityRow.js, src/apps/Permissions/ManageRolePanel.js, src/apps/Permissions/NavigationItem.js, src/apps/Settings/DaoSettings.js, src/components/LocalIdentityBadge/LocalIdentityBadge.js, src/components/LocalIdentityModal/LocalIdentityModal.js, src/components/SignerPanel/ActionPathsContent.js
This addresses comments in https://github.com/aragon/aragon/issues/672
=> Identity - Improve LocalIdentityBadge

src/components/MenuPanel/OrganizationSwitcher/FavoriteRow.js, src/components/MenuPanel/OrganizationSwitcher/Favorites.js, src/components/MenuPanel/OrganizationSwitcher/ItemButton.js, src/components/MenuPanel/OrganizationSwitcher/OrganizationItem.js, src/components/MenuPanel/OrganizationSwitcher/OrganizationSwitcher.js, src/components/Popup.js
Fixes #568
<p align=center> <img width="1000" alt="" src="https://user-images.githubusercontent.com/36158/55641084-59527880-57cd-11e9-9e59-fdc24a93f875.png"><br>Normal state
<p align=center> <img width="1000" alt="" src="https://user-images.githubusercontent.com/36158/55641086-59eb0f00-57cd-11e9-9178-27fb8742f368.png"><br>Focused state
- Add an item to open or create another organization by redirecting to the home screen.
- Move the common focus logic and styling in `ItemButton`.
- The correct label should be something like “Create or open another organization”, but “Open organization…” was chosen to keep it shorter.
- The “…” were used to make it clearer that it is a clickable item, but maybe an icon could do a better job at it? Edit: done, thanks @dizzypaty!
=> Organization switcher: open or create another org

src/components/MenuPanel/MenuPanel.js, src/components/MenuPanel/MenuPanelFooter.js
Borders: consistent colors + use of 1px border vs. height (browser engines round these differently).
Preferences button: the button is now always left aligned + fix inner spacing.
System apps toggle:
- The arrow is now next to the label, vertically aligned, points in the direction of the action (opposite), and is animated.
- The toggle button has an active state.
- Transition + cosmetic tweaks.
~Note about the toggle transition: the plan is to improve it later, after having moved to the latest version of react-spring. I think it could work better visually, and I’d also like it to feel more snappy, but in the react-spring version we are using, keyframe transitions seem to wait for the current step to finish before cancelling the transition. I want to check if it gets fixed after an upgrade …
=> Menu panel tweaks

src/App.js
Coupled with https://github.com/aragon/aragon.js/pull/277, apps will now receive errors on `requestAddressIdentityModification()`.
=> Identity Provider: provide response to aragonAPI when user cancels identity modification

src/App.js, src/Wrapper.js, src/aragonjs-wrapper.js, src/worker-utils.js
Coupled with https://github.com/aragon/aragon.js/pull/267, this allows the client to restart an upgraded app's worker in-place.
We reset the cache on the upgrade as well, as there may be incompatibilities in the reduced state between different worker versions (as well as paired with their frontends). Note that app frontends are handled mostly transparently as we re-load their URL into the iframe upon navigation.
=> feat: restart app worker when upgraded

package.json, src/components/Preferences/Import.js
- Bug fix for non working button
- Because we were not using `getInputProps` on the input (as suggested in react-dropzone docs), `react-dropzone` didn't properly attach the callback or set the ref.
=> Fix import file button

src/onboarding/templates/democracy/ConfigureVotingDefaults.js
Fixes #706.
Opted to keep the manual padding (25px vs. 20px), as with the default the input was a bit too close.
=> fix: align textinput adornment in democracy onboarding

src/components/IdentityBadge/LocalIdentityBadge.js
- Ensure the effect runs when the entity changes
- When changing accounts the custom identity label wouldn't update
=> Ensure the local identity is resolved when the entity changes

src/components/Preferences/Preferences.js
Horizontally centers the close button to be the same margin as the title.
Before:
After:
=> fix: center Preferences' close button

src/Wrapper.js, src/apps/AppCenter/AppCenter.js, src/aragonjs-wrapper.js, src/components/Upgrade/UpgradeOrganizationPanel.js, src/url-utils.js
Oops, we should always be using the repo's latest version to get its base url, not the currently installed version (the one we get from apps) 🙈
=> App Center: correctly use repo's latest version for baseUrl

src/Wrapper.js, src/components/Banner/Banner.js, src/components/Upgrade/HighlightScreen.js, src/components/Upgrade/ProgressBar.js, src/components/Upgrade/UpgradeBanner.js, src/components/Upgrade/UpgradeModal.js, src/hooks.js, src/prop-types.js
- Add a transition on the upgrade banner.
- Add transitions between the highlight screens.
- useSteps(): add the direction.
=> Improve the upgrade modal

src/Wrapper.js, src/apps/AppCenter/InstalledApps/AppContent.js, src/components/Upgrade/UpgradeOrganizationPanel.js
Super small items:
- Avoid rendering the `UpgradeOrganizationPanel` when not necessary
- Filter the list of repos included in the `UpgradeOrganizationPanel` to only include known ones
- Default an app's description in the App Center to "No description." to avoid a dangling header
=> App center polish

package.json, src/apps/AppCenter/InstalledApps/AppContent.js, src/apps/Permissions/AppInstanceLabel.js, src/apps/Permissions/NavigationItem.js, src/apps/Settings/DaoSettings.js, src/components/Preferences/Preferences.js
Builds on top of #750 to avoid conflicts.
=> Refactor Viewport to useViewport hook (for some components)

package.json
Fixes requesting test tokens, as `@aragon/templates-tokens@v1.2.0` didn't include the `depositerABI` in its exports.
=> fix: upgrade @aragon/templates-tokens to version including depositerABI

src/components/Preferences/LocalIdentities.js, src/hooks.js
See https://github.com/aragon/aragon/pull/771/files/2907ecbbf266d6d866c874991de468a00fc49ddc#r282035502
=>  useSteps(): only update setStep when needed

package.json, src/components/Preferences/LocalIdentities.js, src/components/Preferences/Preferences.js
How to test:
```sh
cd into `aragon/aragon`
git fetch
git checkout feature/granular-export-labels
npm i
npm run start
```
- Open up browser to `localhost:3000`
- Click on `Preferences` and test out selectable custom labels for export
- Profit
=> Granular export labels

.eslintrc, package.json, src/components/Activity/ActivityPanel.js, src/components/IdentityBadge/LocalIdentityBadge.js, src/components/LocalIdentityModal/LocalIdentityModal.js, src/components/Preferences/Preferences.js, src/components/Upgrade/UpgradeModal.js, src/components/Upgrade/UpgradeOrganizationPanel.js, src/hooks.js
Similar settings to those in the Voting app.
Was wondering why there were some many missed dependencies in the cached lists :smile:.
Note that there are some unfixed rules in `Preferences/LocalIdentities`; for the sake of simplicity we can fix those after #768.
=> Eslint: add hook rules

package.json, src/components/Activity/ActivityItem.js, src/components/Preferences/EmptyLocalIdentities.js, src/components/SignerPanel/ActionPathsContent.js
Update identity badges to compact mode when is displayed with inline text.
~Requires the master branch of @aragon/ui.~
1- Activity panel:
2- ActionPathsContent
3- EmptyLocalIdentities
=> Update identity badges to compact mode

src/components/HelpScoutBeacon/BeaconHeadScripts.js, src/components/HelpScoutBeacon/HelpScoutBeacon.js
Attempt at making the logic a bit more natural, despite some cumbersome behaviour with how HelpScout's Beacon works (that probably influenced the original design).
Fixes the issue with the `window.Beacon('on')` handlers not being attached properly when `window.Beacon` isn't in the `useEffect()`'s dependency list. The old way of doing this was prone to race conditions, as `window.Beacon` isn't a value inside React, and is fully dependent on the component being re-rendered afterwards to properly attach (rather than triggering the update itself).
Some notes:
- `window.Beacon('on', 'open')` looks like the most fullproof way to actually detect when the modal can be opened; `window.Beacon` (and the script itself) being loaded are not enough
=>  HelpScoutBeacon: move towards an onLoad handler and lift ready state to Beacon itself

src/components/LocalIdentityModal/LocalIdentityModal.js
What was happening:
1. In `LocalIdentityModal`, `props` was recreated on every render (using `...props`).
2. `props` being present in the [`useEffect()` dependencies](https://github.com/aragon/aragon/compare/fix-infinite-rendering?expand=1#diff-4e3064bc49a5abb8223170f44d7b2dd2L14), the effect was running every time the component was re-rendered.
3. This effect was calling [`hideModal()`](https://github.com/aragon/aragon/blob/master/src/components/ModalManager/ModalManager.js#L22) on `ModalProvider`, which updates the state with a new `modalComponentProps` every time it gets called.
4. The state of `ModalProvider` passed to the context provider every time the component is re-rendered…
5. …which was re-rendering LocalIdentityModal. :loop: 
To solve the issue, I destructured `props` and used …
=> Fix infinite rendering loop

src/components/LocalIdentityModal/LocalIdentityModal.js
Turns out these aren't safe as required props, since closing the modal resets all the props.
=> LocalIdentityModal: update required props

src/aragonjs-wrapper.js, src/worker-utils.js
Orphans app WebWorkers to an [opaque origin](https://html.spec.whatwg.org/multipage/origin.html#concept-origin-opaque). Trying to access `indexedDB` now results in an error:
This wasn't a huge issue before, as WebWorkers have no access to `localStorage` or the DOM, but after we introduced `localForage` and `indexedDB` access, these WebWorkers all of a sudden were able to Do Bad Things<sup>TM</sup> (like write to an app's cache at will and influence another app's frontend).
----------
Also gives the WebWorkers some names, for ease of debugging:
=> Apps: orphan app WebWorkers' origins

package.json, src/App.js, src/components/Activity/TimeTag.js, src/components/App/AppLoader.js, src/components/Preferences/Preferences.js, src/components/SignerPanel/ConfirmTransaction.js
[history now recommends using a different import syntax](https://github.com/ReactTraining/history/releases/tag/v4.8.0-beta.0), and a couple of small proptype warnings due to `dao` not being available during onboarding.
=> Fix warnings

src/aragonjs-wrapper.js, src/iframe-worker.js, src/worker-utils.js
Adds extra sandboxing to webworkers by executing them in iframe.
=> Webworker in iframe

src/components/HelpScoutBeacon/suggestions.js, src/components/HelpScoutBeacon/useBeaconSuggestions.js
Migrates the suggestions to use appIds instead, as they're less likely to change (basically impossible ATM).
Fixes #816.
=> HelpScout suggestions: use appIds instead of app names

src/components/HelpScoutBeacon/HelpScoutBeacon.js
Discussion and context:
- https://github.com/aragon/aragon/pull/800#pullrequestreview-242811266
- https://github.com/aragon/aragon/issues/798#issuecomment-496608964
https://www.loom.com/share/b50d00490999450b894f19b10df93728
Implemented in a way that does not prevent interactions with the layers beneath 😄 (no clickable overlay)
=> HelpScout Beacon iframe app blur/clickoutside

package.json, scripts/build-local, scripts/config/local.js, scripts/launch-local
Needed to publish a locally-connected version of the Aragon client to local aragen aragonPM instances.
@0xGabi this will make that published version of the client connect to the localhost RPC **and** localhost IPFS daemon by default (it's similar to what happens on `start:local`). I think this is a valid assumption for the CLI, but not super sure about Aragon desktop.
=> Add build:local script

package.json
Removes the specific delay we applied to work with Infura's inconsistent events.
=> Mainnet: remove artifical event delay

.travis.yml, now-mainnet.json, now-preview.json, package.json, src/environment.js
Builds `preview.aragon.org` on pushes to `newstyle`.
**Note**: this configuration is only meant to be used in the `newstyle` branch during development. We should **NOT** be merging this change into `master`. I've included a note in #826 for this.
=> Now: deploy preview version for newstyle branch

src/components/SignerPanel/SigningStatus.js
Unclear which providers error in this way, but we were erroneously making the assumption that an error thrown from the provider would always contain a message string.
See https://sentry.io/share/issue/54450fea43c74f0e86d2ca4a332121d8/ for an example.
Adds a new message to point the user at something wrong going on with their signing provider in such cases:
=> SignerPanel: fix error cases when Ethereum provider doesn't error with message

src/components/HelpScoutBeacon/HelpScoutBeacon.js
🙈 Oops, forgot to include this required prop.
=> HelpScout: add description to beacon button

src/components/FeedbackIndicator/FeedbackIndicator.js, src/components/SignerPanel/SigningStatus.js
Accompanying changes for [Voting](https://www.notion.so/aragon/Design-review-0-8-items-bf12838cc3874c05811a96722a961ccd) (although these apply everywhere)
=> Sidepanel feedback

src/components/SignerPanel/ActionPathsContent.js, src/components/SignerPanel/AddressLink.js, src/components/SignerPanel/ConfirmMsgSign.js, src/components/SignerPanel/ConfirmTransaction.js, src/components/SignerPanel/ImpossibleAction.js, src/components/SignerPanel/SignMsgContent.js, src/components/SignerPanel/SignerButton.js, src/components/SignerPanel/SignerPanel.js, src/components/SignerPanel/ToggleContent.js, src/components/SignerPanel/Web3Errors.js
Adjusts the signer panel to the new styles:
Feedback statuses are implemented in #907.
----------
Direct:
Web3 not installed:
Provider not enabled:
Action impossible:
-----
TODO:
=> SignerPanel: adjust for new styles

.gitignore, package.json, scripts/build-local
When trying to do the automatic deployment of aragen I notice that the `ui-assets` npm script was still been used by the `build:local` script.
=> Changes to fix aragen automatic deployment

src/components/IdentityBadge/LocalIdentityBadge.js, src/hooks.js
Oops, this must've been missed earlier when cleaning up the CLEAR and adding the REMOVE modes.
Fixes remove not updating labels on the menu panels.
Also consolidates the logic in `LocalIdentityBadge` to use `useLocalIdentity()`.
=> useLocalIdentity: handle remove case

src/components/SignerPanel/ActionPathsContent.js, src/components/SignerPanel/ConfirmTransaction.js, src/components/SignerPanel/SignerPanel.js
Cleans up the props here by adding this metadata into the transformed `intent` object.
cc @dizzypaty I've also added another identity badge (I don't think having more here hurts, since this is such a sensitive thing):
=> SignerPanel: consolidate external transaction props into intent object

src/components/MenuPanel/MenuPanel.js, src/components/OrgView/OrgView.js
- Remove references to the org switcher.
- Spacing / transition tweaks.
- Fix the vertical alignment of the labels.
- Re-add the “slide down” effect on the system apps.
=> MenuPanel tweaks

src/aragonjs-wrapper.js, src/onboarding/Onboarding.js
Supercedes https://github.com/aragon/aragon/pull/897.
See associated PR in aragon.js: https://github.com/aragon/aragon.js/pull/369.
I'll keep the ENS resolution as part of `@aragon/wrapper` for now, until we can remove it completely with something like [`ens-lite`](https://github.com/jefflau/ens-lite).
=> Update ENS API changes from @aragon/wrapper

src/prop-types.js
A few more of these fields can't be considered mandatory because they're fetched from the app's aragonPM repo content, which may or may not be available (depending on IPFS, network, etc.).
=> PropTypes: move fetch-required fields of AppType to be non-required

src/apps/AppCenter/AppCard.js, src/apps/AppCenter/InstalledApps/AppContent.js, src/apps/AppCenter/InstalledApps/RepoVersions.js, src/components/Markdown/Markdown.js
From https://github.com/aragon/aragon/pull/928#issuecomment-527278602:
> Update the app screenshots to ones with the new style
This will have to be checked separately, once we publish the new descriptions.
> The 'Upgrade app' button on the app detail view must be wide (100% minus 2GU padding on each side) when displayed on medium & small viewports
I've done this only for small layouts, as anything above small (medium, larger) has enough room to put the button on the right side.
=> App center: polish from design review

src/App.js, src/Wrapper.js, src/apps/Organization/Organization.js, src/components/Upgrade/UpgradeBanner.js
Fixes https://github.com/aragon/aragon/issues/287.
Lifts the `UpgradeModal` (perhaps we should rename this to `VersionShowcase` or something later) up to be in `Wrapper` so it can be controlled from apps like Organization.
TODO:
=> Organization: add current version details and add link to upgrade showcase

src/components/GlobalPreferences/CustomLabels/LocalIdentities.js
Was working on fixes from [here](https://www.notion.so/aragon/Design-review-0-8-II-eefe2d081a7d49f4b08602f76e50be6a) but have to take another direction, don't want this to get lost:
=> Preferences: adjust spacing in custom labels

src/components/GlobalPreferences/SharedIdentities/useSharedLink.js
For example by changing the URL from `/myorg?preferences=/custom-labels` to `/`.
=> Fix a crash when going to the client home from the preferences

src/apps/Permissions/Permissions.js, src/components/GlobalPreferences/GlobalPreferences.js
After https://github.com/aragon/aragon/pull/971, only the top banner seems to disappearing from using `scrollIntoView`.
=> Permissions: fix the entire view jumping when using scrollIntoView()

src/components/Upgrade/UpgradeOrganizationPanel.js
Oops 🙈, if you had more than just the known apps installed and there were major updates available for them, this would try to also include them in the upgrade.
This now selects only the short list of known repos (Finance, Tokens, Voting) to be part of this "organization upgrade".
Fixes some bugs with the upgrade panel along with https://github.com/aragon/aragon.js/pull/385.
=> Upgrade Org: fix upgrade transaction for orgs with non-known apps

src/components/MenuPanel/OrganizationSwitcher/Favorites.js, src/components/MenuPanel/OrganizationSwitcher/OrganizationSwitcher.js, src/contexts/FavoriteDaosContext.js, src/onboarding2/Welcome/Suggestions.js
I'm surprised we've gotten away for so long without doing this in `FavoritesDao`.
Fixes the issue with seeing duplicates in the org switcher and onboarding's suggestions list.
=> Favourite Organizations: check address equality with checksums included

src/components/Activity/ActivityList.js, src/components/OrgView/GlobalPreferencesButton/GlobalPreferencesButton.js
=> Preferences, Activity: make panels fullwidth on smaller screens

src/components/GlobalPreferences/Notifications/SubscriptionsForm.js
- Submit the ABI with all events when creating a subscription. 
- The ABI is used to create eventsources which are shared across subscriptions for polling events. Because subscriptions can be to unique events, we need to have the ABI with all the events.
=> Send the full abi for the eventsource

src/components/GlobalPreferences/Network/Network.js
=> Preferences: update network settings' buttons to be fullwidth on small layouts

src/templates/company/index.js
Oops 😄
The company template's stakes should not be locked.
=> Onboarding: allow token stakes to be defined

src/components/Carousel/Carousel.js
@bpierre 
This is just a hack and by no means a proper fix. It simply disables alpha animations and adds a multiplier to the drag delta to overcome getting stuck without having to deal with velocity yet.
=> Hacks to work around current carousel bugs

src/components/GlobalPreferences/GlobalPreferences.js
Replaces the Preferences' tab bar with a visually similar version when there's only one item.
This is just for now; we should eventually handle this better in aragonUI: https://github.com/aragon/aragon-ui/issues/595.
Currently:
With the change:
=> Onboarding: remove preferences having empty tabs in small viewports

src/onboarding2/Create/Create.js, src/onboarding2/Templates/TemplateDetails.js, src/onboarding2/Templates/Templates.js, src/templates/company/index.js, src/templates/membership/index.js, src/templates/reputation/index.js
Passes the optional modules to each template's `prepareTransactions()`.
=> Onboarding: add Agent as optional module

src/apps/Permissions/AppPermissions.js, src/apps/Permissions/AssignPermissionPanel.js, src/apps/Permissions/Home/AllPermissions.js, src/apps/Permissions/Home/Home.js, src/apps/Permissions/ManageRolePanel.js, src/apps/Permissions/Permissions.js, src/apps/Permissions/PermissionsIdentityBadge.js, src/apps/Permissions/PermissionsView.js, src/contexts/PermissionsContext.js, src/permissions.js
Also adds a few stylistic changes as noted by @dizzypaty.
Features:
- Context menu actions
- Show unassigned roles in app view
All "entities" are now being shown as IdentityBadges:
=> Permissions: bring back to feature parity with old version

src/App.js, src/components/GlobalPreferences/Notifications/AppLabel.js, src/components/GlobalPreferences/Notifications/SubscriptionFilters.js, src/components/GlobalPreferences/Notifications/SubscriptionsForm.js, src/components/GlobalPreferences/Notifications/SubscriptionsTable.js, src/components/LocalLabelAppBadge/LocalLabelAppBadge.js, src/components/LocalLabelAppBadge/LocalLabelPopoverActionLabel.js, src/components/LocalLabelAppBadge/LocalLabelPopoverTitle.js
=> Notifications: sprinkle AppBadges all around

src/routing.js
Quick fix until we rename `getAppPath()` and refactor the routing system a bit.
=> Fix the redirection when closing the global settings on the onboarding

.travis.yml, now-preview.json, package.json, src/environment.js
Reverts the change to publish nightly builds onto `preview.aragon.org` from https://github.com/aragon/aragon/pull/898.
=> chore: deploy nightly builds back on nightly.aragon.org

src/components/GlobalPreferences/Notifications/NotificationsLogin.js, src/components/GlobalPreferences/Notifications/SubscriptionsForm.js, src/components/GlobalPreferences/Notifications/notification-service-api.js
cc @2color moved the network sanitization to be embedded in the API calls themselves.
=> Notifications: use sanitized network type for service

src/templates/company/index.js, src/templates/fundraising/index.js, src/templates/kit/Navigation.js, src/templates/kit/index.js, src/templates/kit/screens/ClaimDomainScreen.js, src/templates/kit/screens/ReviewScreen.js, src/templates/kit/screens/TokensScreen.js, src/templates/kit/screens/VotingScreen.js, src/templates/membership/index.js, src/templates/reputation/index.js
- Remove longDesc and caseStudyUrl template entries (until we need them).
- Move and rename the screen components into screens/.
- Add a prop type for screen-specific props.
- Unify the way screen components accept screen-specific props.
- Rename PrevNextFooter => Navigation.
=> Templates kit cleanup

src/onboarding/Templates/TemplateDetails.js
Users are used to referring to these bits of code as "apps", not "modules", and we don't call them "modules" anywhere else in the frontend.
=> Rename "modules" to "apps"

src/components/GlobalPreferences/CustomLabels/CustomLabels.js, src/components/GlobalPreferences/CustomLabels/LocalIdentities.js, src/components/GlobalPreferences/CustomLabels/useLocalIdentities.js, src/components/GlobalPreferences/CustomLabels/useSelectIdentities.js, src/components/GlobalPreferences/CustomLabels/useSort.js
This change makes it so that whenever `identities` change then the selection is reset (all selected).
Sorting was resetting the selected identities so now these changes include a decoupling of sorting as an independent hook
=> Custom labels reset selection on import

src/onboarding/Configure/ConfigureTemplateScreens.js, src/onboarding/Header/Header.js, src/onboarding/Templates/TemplateDetails.js, src/templates/kit/Duration.js, src/templates/kit/index.js, src/templates/kit/screens/ClaimDomainScreen.js, src/templates/kit/screens/TokensScreen.js, src/templates/kit/screens/VotingScreen.js, src/url-utils.js
- `TokensScreen` review summary: display the amount of tokens in front of each account.
- `ConfigureTemplateScreen`: always use the maximum width.
- Templates kit: add `Duration`.
- `stripUrlProtocol()`: also remove the final slash.
- `onboarding/Header`: use a `<div>` for the subtitle to allow nested block elements.
- `TemplateDetails`: apps / required apps fixes.
- Ensure each checkbox has its own label.
- Remove the default height.
- Remove the custom styles on the checkboxes.
- `TemplateDetails`: display the user guide URL.
- `TokensScreen` / `VotingScreen`: prevent the entire data to be overwritten (when `dataKey` was set to `null`).
- `TokensScreen`: allow to not have any member.
- `TokensScreen` subtitle: custom label + use AppBadge.
- `VotingScreen` subtitle: custom label + use …
=> Templates: various fixes

src/components/GlobalPreferences/CustomLabels/CustomLabels.js, src/components/GlobalPreferences/CustomLabels/LocalIdentities.js, src/components/GlobalPreferences/CustomLabels/useFilterIdentities.js
With these changes larger screens use `SearchInput`. Smaller screens have extra functionality, that's why this is only implemented for larger screens.
Passes down `setSearchTerm` as `SearchInput` has a different API to `TextInput` (discussion with @bpierre about inputs sending the value + the event); when the API for inputs is updated this can be refactored into using only one handler.
=> Custom labels: refactor large screens to use SearchInput component

package.json
Fixes the missing `SearchInput` error.
=> Upgrade @aragon/ui to 1.0.0-alpha.27

src/components/FavoritesMenu/FavoritesMenu.js, src/components/FavoritesMenu/FavoritesMenuItem.js, src/components/MenuPanel/OrganizationSwitcher/Favorites.js, src/components/MenuPanel/OrganizationSwitcher/OrganizationItem.js, src/components/OrgIcon/OrgIcon.js, src/onboarding/Welcome/Suggestions.js
Abstracts the organization image into an `OrgIcon` component, similar to `AppIcon`.
Also fixes a few small things with alignments / etc.
=> Favorites: display identicons for known orgs

src/templates/kit/screens/ClaimDomainScreen.js, src/templates/kit/screens/ReviewScreen.js, src/templates/kit/screens/TokensScreen.js
Just removing some default params to use `defaultProps` instead.
=> Onboarding: minor fixes

src/components/Error/ErrorScreen.js, src/onboarding/Onboarding/OnboardingTopBar.js
After the last update (bbb1038a10dcb1556a0822fcff2dd59495170b1b) the prop
and imports were not removed.
=> OnboardingTopBar: remove unneeded prop type

src/onboarding/Templates/TemplateDetails.js
cc @dizzypaty we may want to come up with a different way of displaying this information in the future. As it is, it's a bit confusing—is it all the installed apps, or just the ones I'm configuring?
From our earlier conversations, we meant it to be only the apps that were being configured, but that also doesn't do a great job of advertising that a template is doing So Much More<sup>TM</sup>.
E.g. on our Reputation template, we don't show the Vault (for good reason—it doesn't have a UI), but we do show the Finance app, even though it's not being configured:
For the Open Enterprise template, we show all the apps, even though most of them don't have any configuration:
-----
Perhaps we could use a different section and visual indicator to denominate the apps that require configuration?
The …
=> Templates: update copy from 'required apps' to 'included apps'

src/apps/Permissions/AppPermissions.js
Fixes https://github.com/aragon/aragon/issues/1158
The passed `app` object can be undefined, which now shows the loading state.
=> Permissions: fix a crash when an app is active during load

.eslintrc.js
I think we may have introduced this rule with a warning initially to avoid having to fix all of them in one go, but we've now either set up specific areas to ignore, or have already fixed all of them so we should lift it up to be an error :).
=> ESLint: error on react hook dependency issues

src/components/OrgIcon/OrgIcon.js
Chrome seems to have introduced a bug where setting a `mask-image` results in a higher-level overflow to not work (see rinkeby.aragon.org with latest Chrome).
This moves the border-radius to be applied directly at the level that the `mask-image` is applied.
=> OrgIcon: fix border radius in Chrome

src/Wrapper.js
This was meant as a bit of a timebomb we would change as future deployments happened.
Was debating whether or not we should keep this stubbed in case we wanted to re-open the modal in future versions, but we can just revert this and change the localstorage keys at that time.
Thoughts?
=> UpgradeModal: remove automatic opening of upgrade modal

src/wallet.js
Some mobile browsers were complaining about destructuring.
They only complain about the destructuring with the `newBlockHeader` subscription, which is something we should remove anyway (#1214), but didn't see much point in destructuring the wallet web3 instance either.
=> AccountModule: fix crashes on mobile

src/wallet.js
- Changes the `WalletBlockNumberProvider` to use a simple 5s polling timer for fetching the latest block.
Closes #1214
=> Change block polling mechanism to 5s poll rate

manifest.json
I think this has changed since a long time ago, but might as well update it since the `index.html` is now in the root of the deployed folder.
=> chore: update manifest's start_url

src/onboarding/Deployment/Deployment.js
We were using `row-reverse` for this prop :).
We also switch to `display: grid` when `column` is used (https://github.com/aragon/aragon/blob/master/src/onboarding/Deployment/Deployment.js#L61); should we do the same for `column-reverse`?
=> Onboarding: fix prop types

src/components/MenuPanel/MenuPanel.js
- Opens the system menu when one of the corresponding app instances becomes active.
Closes #1224
=> Automatically open the system menu when a system app instance is active

src/App.js
Oops, I think `wrapper` is never passed as props in `App.js` so I think this is what we actually meant?
=> guiStyle: fix logic for setting initial guiStyle

src/components/SignerPanel/ActionPathsContent.js
Fixes https://github.com/aragon/aragon/issues/1244 (quick fix to warn users).
=> SignerPanel: Add warning for some Ethereum providers marking second+ transactions as potentially failing

src/apps/Console/ConsoleFeedback.js
- Fix a bug on mobile from the `exec` command: The function signatures were overflowing out of the div.
- Add consistent naming to the act command: instead of `functionSignature(param: arg)`, rename to `methodName(type: arg)`
- Fix rogue ampersands. :)
=> Fix mobile console overflow and add consistent naming to feedback component

docs/CONSOLE.md
Adds documentation for the console system app, along with examples on how to use it. 🙌
Tasks:
This PR fixes #1287
=> Add console documentation

src/templates/kit/screens/FundraisingScreen.js
Hey there were a small typo on the `SlippageLabel` that always show DAI as preview message.
Also I notice there is a Slippage form for ANT but there is no ANT functionality yet. Is it necessary?
=> Onboarding: small fixes to slippage tooltips

src/components/Markdown/Markdown.js
As found in the Court Dashboard 😅. We weren't passing down props into the `Link`.
=> Markdown: fix links being rendered without an href

scripts/start
We have degraded `wss://mainnet.eth.aragon.network/ws` connections on non-whitelisted domains, so it is very likely that developers connecting to mainnet will experience very slow loading.
In lieu of a better immediate fix, this provides some warning to the developer that they should override these configs via environment variables.
cc @Evalir
=> docs: warn dev when starting mainnet locally to use a different ETH node

src/components/ConnectModal/ConnectModal.js
The connect modal was only connecting to the injected provider, and not intercepting errors.
This change removes any connection attempt from the modal, and invite users to close it so they can use the account module instead.
=> Connect modal: let users close the modal and use the account module

src/components/GlobalPreferences/CustomLabels/CustomLabels.js, src/components/GlobalPreferences/CustomLabels/LocalIdentities.js, src/components/GlobalPreferences/CustomLabels/useFilterIdentities.js
This seems like something the linter would pick up as an unused variable, but maybe it doesn't do that for unused props.
We had duplicated the export of `setSearchTerm` as `handleSearchTermChange` previously expected an event object.
=> GlobalPreferences: clean up search handlers for local identities

src/components/GlobalPreferences/GlobalPreferences.js
At least on Chrome browsers, the GlobalPreferences modal would show the default native focus outline if it was short enough (e.g. on an unpopulated local labels tab).
=> GlobalPreferences: remove focus outline

package.json, src/network-config.js
When run locally, the providers component didn't display the icons properly:
The problem was in the `networkConfigs` variable where providers have to be arrays of objects instead of arrays of strings.
Thanks @Evalir for the help! 🙌
=> AccountModule: Fix providers component display 

src/apps/Console/ConsoleFeedback.js
Better represent the permissions set for the app that is installed.
See:
- [`ACL.sol` and the `createPermission` params](https://github.com/aragon/aragonOS/blob/next/contracts/acl/ACL.sol#L96)
- [ How the function is called on the `install` command](https://github.com/aragon/aragon/blob/master/src/apps/Console/handlers/install.js#L79)
=> Console: fix permission copy on install command

now-mainnet.json, now.json, src/local-settings.js
Re-applies the change in https://github.com/aragon/aragon/pull/887 and https://github.com/aragon/aragon/pull/890.
Unfortunately, we are still seeing race conditions in our ETH nodes, and this "hotfix" looks like it will have to stay for a while.
The problem manifests itself as:
1. Ethereum event is sent
2. `eth_call`s to fetch state on this event fail
3. An indeterminate amount of time passes before these `eth_call`s work
In an app, like Voting, this usually results in state not being updated correctly because it couldn't find the required information through `eth_call`s.
We have built-in retry logic into our apps to help catch these, but they look like they're still not enough :(.
=> Ethereum: add built-in delay for received events on real networks

src/apps/Permissions/AssignPermissionPanel.js, src/apps/Permissions/ManageRolePanel.js, src/permissions.js
Spring cleaning 🌸, closing #969 .
> ...And you will their engineer, your code will be their shield and your PR... their sword. You will remain... online... for your fight... is eternal.
Adds a warning when using the "safe address" `0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF`, in the permission panels. Screenshots:
=> Permissions: Add "any account" warning when using safe address

src/components/GlobalPreferences/HelpAndFeedback/HelpAndFeedback.js
Spring Cleaning 🌸, closing #1332 
We probably may want to quickly check up with @dizzypaty on this, but, I believe a good place to link to the documentation, is where you "activate" the console itself. Let me know what you think!
=> Documentation: Add console documentation link

src/templates/kit/screens/VotingScreen.js
Reduces the minimum vote duration to be 1 minute. Closes #1093 .
Here's the new error copy when you try to submit a duration lower than one minute (🏎 voting!)
=> Onboarding: make minimum vote duration be 1 minute instead of 10

src/apps/Console/Console.js, src/apps/Console/ConsoleFeedback.js, src/apps/Console/console-utils.js, src/apps/Console/console-utils.test.js, src/apps/Console/handlers/install.js
Builds on https://github.com/aragon/aragon/pull/1382.
Primarily aligns the language and implementation of each command. May be easiest to review commit-by-commit.
Main changes:
- 1de2427: updates `CommandFeedback`'s rendering logic to not use `else` unless necessary
- 6db0396: consolidates `CommandFeedback`'s styling into internal components
- e5201e0, 55ed113, 9979441: several prop name or internal alignments with rest of codebase
- 8d4fa7f: fix install for apps with app names that differ from their display names
- 44facf6: UX enhancement: overwrite incomplete command arguments if user clicks on an interactive command
----------
How `act/` looks:
=> Console: update and align copy, refactor internals

src/onboarding/Configure/Setup.js, src/onboarding/Create/Create.js
This PR closes #1297 
From a convo with @bpierre we thought that since the `<ConfigureTemplateScreens>` and `<Templates>` shares lot of styes from the Parent screen doesn't make much sense to remove the `ConfigureTemplateScreens` from there, so we thought about  a better naming for the `Configure` screen
=> Onboarding: Rename configure screen

.github/workflows/mainnet.yml, .github/workflows/tests.yml
Updates the deploy workflow to use yarn instead of npm.
Also fixes the `steps` indentation for the `tests` workflow; this isn't technically wrong (yaml treats the `-` already as an indent), but it does align this workflow to the style shown in Github's Actions documentation.
=> CI: update deploy workflow

src/apps/Organization/Organization.js
Updates Tenderly to use tenderly.co instead of tenderly.dev
=> Organization: update Tenderly integration URL

src/app-locator.js, src/components/Activity/ActivityItem.js, src/components/GlobalPreferences/Notifications/NotificationsLogin.js, src/utils.js
Fixes some of https://github.com/aragon/aragon/issues/1425 (will repurpose that issue with the single remaining item):
- Update the email regex
- Update placeholder email to be example.org
And a few other small items:
- Updates the email input adornment patter
- Updates pattern for using `transformAddresses()`
- Remove cssgu (only used sparsely, and we should prefer babel plugin in the future)
=> Updates from Court Dashboard

src/worker/SandboxedWorker.js
Chrome 83+ appears to have made starting workers reliant on an object URL being available.
This must be an asynchronous race condition with the web worker now being starting asynchronously and sharing memory for the object URL. Revoking the object URL synchronously results in an 100% failure rate; using a `setTimeout(0)` results in it only failing some times.
=> Worker: delay object URL clean up

src/security/configuration.js
See https://www.chromestatus.com/feature/5706745674465280.
This was another security change from Chrome 83 that resulted in some apps with export/download functionality not working anymore.
=> Apps: allow downloads from iframe

package.json, src/apps/AppCenter/InstalledApps/AppContent.js, src/apps/AppCenter/InstalledApps/ContentMarkdown.js, yarn.lock
Removes `remark` and `remark-react` in favour of the [Markdown component](https://devbox.dweb.cool/#Markdown) in `@Aragon/ui`
=> App Center: Markdown via @aragon/ui

package.json, src/date-utils.js, yarn.lock
Upgrade dayjs to support duration and provide helper util for converting to hours.
Use case: https://github.com/aragon/aragon/pull/1446#discussion_r446139808
=> Date utils: Add durationToHours()

src/apps/Permissions/AppPermissions.js, src/apps/Permissions/Home/AllPermissions.js, src/apps/Permissions/Home/Home.js
Fixes some prop types errors caused by https://github.com/aragon/aragon/pull/1385 missing required changes for `AppPermissions`.
=> Permissions: fix prop types errors with not controlling the page in AppPermissions

src/components/SigningModals/TransactionJourney.js
Accepts array of items where you can define the `title` `icon` and generic `content`.
Pass an index to `activeItem` to decide which part of the "journey" to highlight. Optional `pulse` will either render a pulsing pip or a solid unbroken border.
```<TransactionJourney items={journeyItems} activeItem={activeIndex} pulse />```
```
[
'Title 1',
{
icon: myIcon,
content: <p>My content</p>,
},
],
[
'Title 2',
{
icon: myIcon,
content: <p>My content</p>,
},
],
....
```
Uses css filters to avoid us having to author multiple icon assets.
=> Signing modals: Add generic TransactionJourney

src/components/SigningModals/MultiScreenModal.js, src/components/SigningModals/prop-types.js
Provide basic configuration for each step via an array of objects. Each screen component gains access to `prevScreen` `nextScreen` and `closeModal` via render prop to manage navigation. Can optionally provide a `width` or use the `disableClose` flag to disable closing behaviour for a specific screen.
```
const screens = [
{
title: 'Screen 1',
content: props => <Screen1 modalProps={props} />,
},
{
title: 'Screen 2',
content: props => <Screen2 modalProps={props} />,
disableClose: true
},
......
]
```
=> Signing modals: Generic multiple screen modal

HACKS.md, package.json, src/ethereum-providers/index.js, src/index.html, src/local-settings.js, src/network-config.js, src/wallet.js, yarn.lock
Closes #1368, closes #1203 .
**Note: for this fix to work we need to update `use-wallet` and `web-react` with the required changes first.**
Web3.js has been mutating the `ethereum` object and wreaking havoc when connecting to a local chain. This is due to the mutation breaking the `send` method, which is unable to fetch the `chainId`, which makes both `use-wallet` and `web3-react` fail.
For this fix to work, we're shallow-cloning the ethereum object into another key in the window object in a script placed right before the react script (this is the "hack"). We're also passing a new prop to use-wallet so we can override the `getLibrary` method we pass to web3-react: https://github.com/aragon/use-wallet/blob/master/src/index.js#L373
We should also, on web3-react, submit a PR to be able to …
=> Local Connection: Add client fixes for connecting to a local chain

package.json, yarn.lock
_No purses were harmed in the making of this PR_.
Bumps `use-wallet` to `0.7.1`, its latest release with improvements for detecting the Goerli, xDai and local testnet.
=> Dependencies: bump use-wallet up to 0.7.1

src/components/AccountModule/connection-hooks.js, src/network-config.js
On local networks that are not simulating block mining, the Account Module eventually will show there may be sync issues / no connection due to it not detecting any activity on-chain. This is desired behavior, but we need to avoid it on local chains.
=> AccountModule: Bypass connection hooks on local / unknown networks

src/GlobalErrorHandler.js, src/index.js, src/routing.js, src/sentry.js, src/utils.js
See https://github.com/aragon/aragon/pull/1457#discussion_r448635887.
I didn't add the `SENTRY_DOMAIN` configuration yet, because I couldn't find an easy, obvious way to match `window.location.href` with a wildcard rule like `*.aragon.org` (though certainly this must exist and be easy!).
------
May need to be updated if #1475 is merged.
=> Sentry: initialize on app start, and add utility for logging to it

src/components/GlobalPreferences/HelpAndFeedback/HelpAndFeedback.js
Oops, we ended up missing this too in the last change for `routing.update()`!
May fix https://sentry.io/share/issue/b3a6881f8632467d8216afd76f180e05/.
=> Preferences: fix link to console app

src/hooks.js
Previously `useSteps` would always revert to first position causing problems in consumers that want to dynamically update collection lengths without disrupting the user experience.
=> useSteps: Remember current step when count changes

src/components/SigningModals/MultiScreenModal.js
Previously, updates to `screens` might throw if the new length was less than the current step.
Persistence of current `step` addressed here https://github.com/aragon/aragon/pull/1480
=> Signing Modals: Support dynamic updates to screens count

HACKS.md, package.json, src/components/SigningModals/TransactionStepper/Step/Divider.js, src/components/SigningModals/TransactionStepper/Step/Illustration.js, src/components/SigningModals/TransactionStepper/Step/StatusVisual.js, src/components/SigningModals/TransactionStepper/Step/Step.js, src/components/SigningModals/TransactionStepper/TransactionStepper.js, src/components/SigningModals/TransactionStepper/stepper-statuses.js, src/components/SigningModals/TransactionStepper/useStepperLayout.js, src/hooks.js, yarn.lock
Takes an array of items consisting of a `title` and async function:
```javascript
const steps = [
['First transaction', handleSign],
['Second transaction', handleSign],
.....
]
```
This function is given access to several props for managing the status of a given step:
`setStepHash`
`setStepWorking`
`setStepError`
`setStepSuccess`
The initial status is always `prompting`:
```javascript
async function handleSign({
setStepHash,
setStepWorking,
setStepError,
setStepSuccess,
}) {
try {
await walletInteraction()
setStepWorking()
const transactionHash = await transactionHash()
setStepHash(transactionHash)
await transactionMining()
setStepSuccess()
} catch (err) {
setStepError()
}
}
```
You can provide an optional callback to the component which fires when all steps have succeeded. Success being …
=> Signing modals: Tx stepper

.github/auto_assign.yml
Adding @andy-hook to the default list of reviewers 🙌.
The bot will randomly pick two from the list on each PR :).
=> chore: add @andyhook to reviewers list

src/components/SigningModal/TransactionStepper/Step/Step.js, src/components/SigningModal/TransactionStepper/TransactionStepper.js
Address https://github.com/aragon/aragon/pull/1473#discussion_r451032237
```javascript
const descs = {
waiting: 'waiting desc',
prompting: 'prompting desc',
error: 'error desc',
working: 'working desc',
success: 'success desc',
}
const steps = [
{
title: 'First transaction',
descriptions: descs,
handleSign: handleSign,
},
{
title: 'Second transaction',
descriptions: descs,
handleSign: handleSign,
},
]
```
=> Signing Modal: Add desc prop to step with defaults

src/components/GlobalPreferences/CustomLabels/useIdentitiesActions.js
Fixes https://github.com/aragon/aragon/issues/1492.
I think this was changed during the routing update (#1272), and although I would agree we shouldn't need an organization context to have this link work, unfortunately we only create a `wrapper` instance when inside of an organization at the moment.
=> Preferences: add organization name to share labels link

README.md, docs/CONFIGURATION.md, docs/FRONTEND_SETUP.md
General search and replace for npm to yarn in the docs.
The only really important commands to update were any instructions with `npm install`, but I thought we might as well use yarn as much as possible.
=> docs: update instructions to be yarn-based

yarn.lock
Adds support for a few more of Decentraland's known functions.
=> chore: update radspec to v1.9.0

.github/workflows/mainnet.yml, now-mainnet.json, now.json
The deployment github action is now targetting the `agreement` branch and deploying to `agreement.aragon.org` and `agreement-rinkeby.aragon.org`.
=> Agreement: add feature deployments to agreement.aragon.org

src/components/SigningModal/TransactionStepper/Step/StatusVisual.js, src/components/SigningModal/TransactionStepper/Step/Step.js, src/components/SigningModal/TransactionStepper/TransactionStepper.js, src/components/SigningModal/TransactionStepper/stepper-statuses.js
The stepper is going to handle these info messages and retry function for now, in the future it should probably be hoisted out and managed separately depending on how complex things get.
=> Signing modal: Add retry and stepper info message

src/templates/dandelion/config/screens/RedemptionsScreen.js
Previously, the description only specified ERC-20 tokens. However, ETH (which is not an ERC-20) is also a redeemable token.
=> Onboarding: clarify which tokens are redeemable for Dandelion organizations

src/components/OrgView/OrgView.js, src/components/SignerPanel/SignerPanel.js, src/components/SigningModal/AddressLink.js, src/components/SigningModal/DetailField.js, src/components/SigningModal/InfoField.js, src/components/SigningModal/MultiScreenModal.js, src/components/SigningModal/SignMessageFlow.js, src/components/SigningModal/SignTransactionFlow/AnnotatedDescription.js, src/components/SigningModal/SignTransactionFlow/SignTransactionFlow.js, src/components/SigningModal/SignTransactionFlow/TransactionDetails.js, src/components/SigningModal/SignTransactionFlow/useSignTransaction.js, src/components/SigningModal/SignerButton.js, src/components/SigningModal/SigningModal.js, src/components/SigningModal/TransactionStepper/Step/Step.js, src/components/SigningModal/Web3Errors.js, src/components/SigningModal/prop-types.js, src/components/SigningModal/useWalletError.js, src/components/SigningModal/utils.js
Apologies for length, it's worth going commit by commit.
Much of this code was adapted from the existing `SignerPanel`. The biggest change is the forking of the code path to not mix message signing state with transaction signing as I feel it's a little easier to reason about this way. I'm not super happy with parts of this due to working around some outstanding issues in the Modal and the way the data is provided and updated.
In general the whole "reshaping" of the bag just feels a bit.. odd, I'm sure there are historic reasons for it in the signer panel but i'd like some feedback on it.
Account connect prompt will come in a separate improvement.
=> Signing modal: 1 – Connect to signature and transaction bags

src/App.js, src/analytics.js, src/components/AccountModule/AccountModuleConnectedScreen.js, src/onboarding/Templates/TemplateDetails.js, src/routing.js
- Enable segment analytics 
- 2 test event is implemented 
- track pages
- track user identification 
important: REACT_APP_ANALYTICS_KEY with aproperate key needs to be set on deployment
=> Enable analytics on v1 DAO-57

src/onboarding/Onboarding/Onboarding.js, src/templates/index.js
=> Re-order templates DAO-48

src/components/AccountModule/AccountModuleErrorScreen.js, yarn.lock
The fix for this involved the changes in [use-wallet](https://github.com/aragon/use-wallet/commit/358d609e812a37c4fce1c5b53a410e5f79b5f3e3) and the client error screen.
=> DAO-90 unsupported network error

.github/workflows/tests.yml
This is a temporary workaround to make the CI test to pass. The proper fix is to use the use-wallet npm package instead of github url.  Once use-wallet 0.9.0 is published, remove `--network-concurrency 1`
=> DAO-104 CI job error

src/network-config.js, src/templates/dandelion/components/TokenSelector/TokenSelectorInstance.js, src/templates/dandelion/config/helpers/getBlockTime.js, src/templates/dandelion/config/helpers/tokens.js, src/templates/dandelion/config/screens/RedemptionsScreen.js, src/templates/dandelion/config/screens/TokenRequestScreen.js
This fix is needed for DAO creation to work for Dandelion template... Without this fix, we can move to next screen.
Other issues to be fixed later:
1) ETH/MATIC descriptive name no longer displays on the DAO creation screen.
2) MATIC still uses ETH's icon
3) After DAO is successfully created, apps not loading, and have unknown name/logo on permission/apps center...
=> DAO-308: Set Polygon DAI address

src/apps/GovernMigration/GovernMigration.js
The `GenerateMigration` method used in `GovernMigration.js` expects the the network to be 'mainnet' (on Ethereum mainnet). However, we're passing 'main'. This PR addresses this issue.
=> Hotfix: Migration generator

src/components/NetworkIndicator/NetworkIndicator.js
This PR hide the network indicator label next to the wallet connector module, when a wallet is connected.
=> Fix: Hide network indicator DAO-270

src/network-config.js
This change allows the DevOps team to have better control over which node gets used on client.aragon.org for the polygon network
Issue: #1687
=> switch polygon connection to proxy deployment
